project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left:
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1A
            href: Hands-on_Ex1/Hands-on_Ex1a.qmd
          - text: Hands-on Exercise 1B 
            href: Hands-on_Ex1/Hands-on_Ex1b.qmd
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_Ex1.qmd
      - text: Take-home Exercises
        menu: 
          - text: Take-home Exercise 1
            
          - text: Take-home Exercise 2
    right:
      - href: index.qmd
        text: Home
      #- about.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    toc-title: "On this page"
    number-sections: true 

editor: visual

