project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left:
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1A
            href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1a.qmd
          - text: Hands-on Exercise 1B 
            href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1b.qmd
          - text: Hands-on Exercise 2A
            href: Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2a.qmd
          - text: Hands-on Exercise 2B
            href: Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2b.qmd
          - text: Hands-on Exercise 3
            href: Hands-on_Ex/Hands-on_Ex3/Hands-on_Ex3.qmd
          
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_Ex1.qmd
          - text: In-class Exercise 2A
            href: In-class_Ex/In-class_Ex2/In-class_Ex2a.qmd
          - text: In-class Exercise 2B
            href: In-class_Ex/In-class_Ex2/In-class_Ex2b.qmd
          - text: In-class Exercise 2C
            href: In-class_Ex/In-class_Ex2/In-class_Ex2c.qmd
          - text: In-class Exercise 3
            href: In-class_Ex/In-class_Ex3/In-class_Ex3.qmd
          - text: In-class Exercise 4
            href: In-class_Ex/In-class_Ex4/In-class_Ex4a.qmd
          - text: In-class Exercise 5
            href: In-class_Ex/In-class_Ex5/In-class_Ex5a.qmd


      - text: Take-home Exercises
        menu: 
          - text: Take-home Exercise 1
            href: Take-home_Ex/Take-home_Ex1/Take-home_Ex1.qmd
          - text: Take-home Exercise 2
            href: Take-home_Ex/Take-home_Ex2/Take-home_Ex2a.qmd


    right:
      - href: index.qmd
        text: Home
      - icon: linkedin 
        href: https://www.linkedin.com/in/gohsihui/ 
        aria-label: LinkedIn
      #- about.qmd
  page-footer:
    background: light
    left: 
      - href: https://quarto.org/
        text: "Published with Quarto |"
      - href: https://www.netlify.com/
        text: "Hosted by Netlify"

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    toc-title: "On this page"
    number-sections: true
    toc-expand: 3
    toc-depth: 3
    
editor: visual

