project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left:
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1A
            href: Hands-on_Ex1/Hands-on_Ex1a.qmd
          - text: Hands-on Exercise 1B 
            href: Hands-on_Ex1/Hands-on_Ex1b.qmd
    right:
      - href: index.qmd
        text: Home
      #- about.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

