---
title: "Take-Home Exercise 2: Applied Spatial Interaction Models - A Case Study of Singapore Public Bus Commuter Flows"
author: "Goh Si Hui"
date: 2023/12/08
date-format: long
date-modified: "last-modified"
format: html 
execute: 
  echo: true
  eval: true
  warning: false
editor: visual 
---

## Overview 

### Introduction 

What are the driving forces behind urban dwellers to weak up early in morning to commute from their home locations to their work places? What are the impact of removing a public bus service on the commuters reside along the corridor of the bus route? These are some questions faced by transport operators and urban managers.

To answer these many questions related to urban mobility, traditionally commuters survey would be used. However, conducting commuters survey is costly, time-consuming and laborious. In addition, survey data tend to take a long time to clean and analyse, which can lead to the collected information being out-of-date when the survey report was ready.

With the recent trend of massive deployment of pervasive computing technologies such as GPS on the vehicles and SMART cards used by public transport commuters, we will utilise and transform geospatially-referenced data into insightful information, hence generating returns on the investment made to collect and manage this data.

### Objectives 

In this take-home exercise, we will be using publicly available data and geospatial data science and analysis to answer questions related to urban mobility and how it can be used to support decision-making. In particular, we will be building spatial interaction models to determine factors affecting urban mobility patterns of public bus transit.

### Packages Used 

For this exercise, we will be using the following packages:

-   **sf** : to import, integrate, process and transform geospatial data

-   **sp**: to provide classes and methods for spatial data types 

-   **DT**:to display R data objects (matrices or data frmaes) as tables on HTML pages

-   **performance**:to compute measures for assessing model quality 

-   **reshape2**:to restructure and aggregate data 

-   **tidyverse**: to import, integrate, wrangle and visualise data

-   **tmap**: to create thematic maps

-   **ggpubr**: to create and customise 'ggplot2'- based publication ready plots 

```{r}
#| code-fold: true 
#| code-summary: "Show the code" 

pacman::p_load(tmap, sf, sp, DT, performance, reshape2, ggpubr, tidyverse) 
```

## Data Preparation 

For the purpose of this take-home exercise, we will be using the following datasets downloaded from LTA Datamall, Data.gov.sg and provided by the course instructor:

Geospatial Data 


Aspatial Data 


### Importing Data into R 

### Data Wrangling of aspatial data

### Data Wrangling of spatial data

## Computing Distance Matrix 

## Preparing Flow Data 

## Preparing Origin and Destination Attributes 

## Geovisualisation of OD flows 

## Calibrating Spatial Interaction Models 

### Unconstrained Models 

### Origin constrained 

### Destination constrained 

### Doubly constrained Model
