<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Goh Si Hui">
<meta name="dcterms.date" content="2023-11-18">

<title>ISSS624 - In-class Exercise 1: My First Date with Geospatial Data Analytics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS624</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Hands-on Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1a.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 1A</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1b.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 1B</span></a>
  </li>  
        <li class="dropdown-header">Hands-on Exercise 2A</li>
        <li class="dropdown-header">Hands-on Exercise 2B</li>
        <li class="dropdown-header">Hands-on Exercise 2C</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">In-class Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex1/In-class_Ex1.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 1</span></a>
  </li>  
        <li class="dropdown-header">In-class Exercise 2</li>
        <li class="dropdown-header">In-class Exercise 3</li>
        <li class="dropdown-header">In-class Exercise 4</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Take-home Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li class="dropdown-header">Take-home Exercise 1</li>
        <li class="dropdown-header">Take-home Exercise 2</li>
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/sihuihui" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/gohsihui/" rel="" target=""><i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link active" data-scroll-target="#getting-started"><span class="header-section-number">1</span> Getting Started</a></li>
  <li><a href="#preparing-the-aspatial-data" id="toc-preparing-the-aspatial-data" class="nav-link" data-scroll-target="#preparing-the-aspatial-data"><span class="header-section-number">2</span> Preparing the Aspatial Data</a>
  <ul class="collapse">
  <li><a href="#importing-the-origin-destination-od-data" id="toc-importing-the-origin-destination-od-data" class="nav-link" data-scroll-target="#importing-the-origin-destination-od-data"><span class="header-section-number">2.1</span> Importing the Origin Destination (OD) data</a></li>
  <li><a href="#extracting-the-study-data" id="toc-extracting-the-study-data" class="nav-link" data-scroll-target="#extracting-the-study-data"><span class="header-section-number">2.2</span> Extracting the Study Data</a></li>
  </ul></li>
  <li><a href="#preparing-the-geospatial-data" id="toc-preparing-the-geospatial-data" class="nav-link" data-scroll-target="#preparing-the-geospatial-data"><span class="header-section-number">3</span> Preparing the Geospatial Data</a>
  <ul class="collapse">
  <li><a href="#importing-geospatial-data" id="toc-importing-geospatial-data" class="nav-link" data-scroll-target="#importing-geospatial-data"><span class="header-section-number">3.1</span> Importing Geospatial Data</a></li>
  </ul></li>
  <li><a href="#geospatial-data-wrangling" id="toc-geospatial-data-wrangling" class="nav-link" data-scroll-target="#geospatial-data-wrangling"><span class="header-section-number">4</span> Geospatial Data Wrangling</a></li>
  <li><a href="#choropleth-visualisation" id="toc-choropleth-visualisation" class="nav-link" data-scroll-target="#choropleth-visualisation"><span class="header-section-number">5</span> Choropleth Visualisation</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">In-class Exercise 1: My First Date with Geospatial Data Analytics</h1>
<p class="subtitle lead">Lesson 1</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Goh Si Hui </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 18, 2023</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">November 21, 2023</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="getting-started" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="getting-started"><span class="header-section-number">1</span> Getting Started</h2>
<p>We will first load the necessary packages using the following code chunk:</p>
<ul>
<li><strong>tmap</strong>: for thematic mapping</li>
<li><strong>sf</strong>: for geospatial data handling</li>
<li><strong>tidyverse</strong>: for non-spatial data handling</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tmap, sf, tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="preparing-the-aspatial-data" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="preparing-the-aspatial-data"><span class="header-section-number">2</span> Preparing the Aspatial Data</h2>
<section id="importing-the-origin-destination-od-data" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="importing-the-origin-destination-od-data"><span class="header-section-number">2.1</span> Importing the Origin Destination (OD) data</h3>
<p>We will import the <code>Passenger Volume by Origin Destination Bus Stops</code> data set downloaded from <a href="https://datamall.lta.gov.sg/content/datamall/en.html" title="LTA DataMall">LTA DataMall</a> by using <code>read_csv()</code> of <strong>readr</strong> package, which is part of <strong>tidyverse</strong> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>odbus <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/aspatial/origin_destination_bus_202308.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We now take a peek at the imported data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(odbus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>From the above, we see that <strong>ORIGIN_PT_CODE</strong> and <strong>DESTINATION_PT_CODE</strong> are character data type. We should convert these two columns from characters into factors because these two columns contains the bus stop numbers and we will need these bus stop numbers to get the bus stop locations in subsequent steps. We will use <code>as.factor()</code> to convert the data from character to factor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>odbus<span class="sc">$</span>ORIGIN_PT_CODE <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(odbus<span class="sc">$</span>ORIGIN_PT_CODE)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>odbus<span class="sc">$</span>DESTINATION_PT_CODE <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(odbus<span class="sc">$</span>DESTINATION_PT_CODE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Do you know?
</div>
</div>
<div class="callout-body-container callout-body">
<p>In R, factors allow for ordered categories with a fixed set of acceptable values. Typically, we would convert a column from character or numeric class to a factor if we want to set an intrinsic order to the values (“levels”) so they can be displayed non-alphabetically in plots and tables.</p>
<p>If you are interested to read more about factors, this <a href="https://r4ds.had.co.nz/factors.html" title="R for Data Science (2e)">webpage</a> has more interesting information and references.</p>
</div>
</div>
</section>
<section id="extracting-the-study-data" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="extracting-the-study-data"><span class="header-section-number">2.2</span> Extracting the Study Data</h3>
<p>We will extract the study data using <code>filter()</code>, <code>group_by()</code> and <code>summarise()</code> to get our study data (i.e., weekday trips that start from 7am and end before 10am).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>origintrip_7_9 <span class="ot">&lt;-</span> odbus <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(DAY_TYPE <span class="sc">==</span> <span class="st">"WEEKDAY"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(TIME_PER_HOUR <span class="sc">&gt;=</span> <span class="dv">7</span> <span class="sc">&amp;</span> TIME_PER_HOUR <span class="sc">&lt;=</span> <span class="dv">9</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ORIGIN_PT_CODE) <span class="sc">%&gt;%</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">TRIPS =</span> <span class="fu">sum</span>(TOTAL_TRIPS))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s take a look at the study data that we have extracted:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(origintrip_7_9))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="preparing-the-geospatial-data" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="preparing-the-geospatial-data"><span class="header-section-number">3</span> Preparing the Geospatial Data</h2>
<section id="importing-geospatial-data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="importing-geospatial-data"><span class="header-section-number">3.1</span> Importing Geospatial Data</h3>
<p>We will use <code>st_read()</code> from <strong>sf</strong> package to read the geospatial data and use <code>st_transform()</code> from <strong>sf</strong> package to project the data into <strong>svy21</strong> using its ESPG code 3414.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>busstop <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/spatial"</span>, <span class="at">layer =</span> <span class="st">"BusStop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `BusStop' from data source 
  `C:\sihuihui\ISSS624\In-class_Ex\In-class_Ex1\data\spatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 5161 features and 3 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 3970.122 ymin: 26482.1 xmax: 48284.56 ymax: 52983.82
Projected CRS: SVY21</code></pre>
</div>
</div>
<p>From the above, we know that the <code>busstop</code> data is a point feature data frame. There are a total of 5161 features and 3 fields, and it uses the <strong>svy21</strong> projected coordinates system.</p>
<p>Let us take a look at the imported data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(busstop)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will now bring in the master plan subzone dataset using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>mpsz <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/spatial"</span>, <span class="at">layer =</span> <span class="st">"MPSZ-2019"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `MPSZ-2019' from data source 
  `C:\sihuihui\ISSS624\In-class_Ex\In-class_Ex1\data\spatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 332 features and 6 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 103.6057 ymin: 1.158699 xmax: 104.0885 ymax: 1.470775
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<p>From the above, we know that the <code>MPSZ-2019</code> data is a multipolygon feature data frame. There are a total of 332 features and 6 fields, and it uses the <strong>WGS84</strong> geographic coordinates system.</p>
<p>Let us take a look at the imported data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="geospatial-data-wrangling" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="geospatial-data-wrangling"><span class="header-section-number">4</span> Geospatial Data Wrangling</h2>
<p>Combining busstop and mpsz</p>
<p>We will now populate the planning subzone code (<strong>SUBZONE_C</strong>) of mpsz dataframe (multipolyon feature) into busstop (point feature) dataframe.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>busstop_mpsz <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(busstop, mpsz) <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(BUS_STOP_N, SUBZONE_C) <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>busstop_mpsz</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     BUS_STOP_N SUBZONE_C
1346      13099    RVSZ05
5067      13089    RVSZ05
839       06151    SRSZ01
965       13211    SRSZ01
974       13139    SRSZ01
1197      13109    SRSZ01
1338      13119    SRSZ01
2309      06169    SRSZ01
2566      06159    SRSZ01
3028      04321    SRSZ01
3277      13079    SRSZ01
4842      06129    SRSZ01
1064      13101    MUSZ02
2365      04223    MUSZ02
2552      08019    MUSZ02
3542      04339    MUSZ02
4302      04219    MUSZ02
4481      04311    MUSZ02
305       91101    MPSZ05
4156      91111    MPSZ05
1184      14519    SISZ01
972       14089    BMSZ17
1099      14019    BMSZ17
1144      14081    BMSZ17
1312      14101    BMSZ17
1610      14061    BMSZ17
1620      14071    BMSZ17
1989      14231    BMSZ17
2197      14109    BMSZ17
3531      05649    BMSZ17
4550      14221    BMSZ17
504       05629    DTSZ10
1106      05419    DTSZ10
3129      03222    DTSZ10
3799      05651    DTSZ10
4069      05431    DTSZ10
54        03411    SVSZ01
179       03419    SVSZ01
3915      03421    SVSZ01
4036      03339    SVSZ01
50        14281    BMSZ01
668       14171    BMSZ01
790       14059    BMSZ01
795       14159    BMSZ01
1026      14009    BMSZ01
1411      14151    BMSZ01
1433      14139    BMSZ01
1451      14129    BMSZ01
1529      14049    BMSZ01
1893      14161    BMSZ01
2137      14121    BMSZ01
2220      14401    BMSZ01
2373      14021    BMSZ01
2518      14419    BMSZ01
2677      14429    BMSZ01
3138      14119    BMSZ01
3615      14271    BMSZ01
3694      14011    BMSZ01
3898      14409    BMSZ01
4358      14131    BMSZ01
5084      14141    BMSZ01
1032      14239    BMSZ15
1195      14319    BMSZ15
1526      14229    BMSZ15
1709      14379    BMSZ15
2116      14291    BMSZ15
2666      14309    BMSZ15
3366      14381    BMSZ15
3696      14039    BMSZ15
4274      14029    BMSZ15
4468      14389    BMSZ15
4827      14489    BMSZ15
2414      03223    DTSZ09
2699      03241    DTSZ09
515       05641    BMSZ16
1459      10021    BMSZ16
1637      05521    BMSZ16
1933      10011    BMSZ16
2701      10499    BMSZ16
3130      10399    BMSZ16
3535      10041    BMSZ16
4169      05631    BMSZ16
5103      14069    BMSZ16
999       14031    BMSZ14
1674      14299    BMSZ14
2159      14259    BMSZ14
2239      14279    BMSZ14
2601      14249    BMSZ14
3086      14269    BMSZ14
3137      05269    DTSZ07
533       03111    DTSZ08
1619      03071    DTSZ08
3649      03129    DTSZ08
4110      03151    DTSZ08
546       10369    BMSZ11
1008      10071    BMSZ11
1535      10051    BMSZ11
1600      10391    BMSZ11
1761      10501    BMSZ11
2175      10361    BMSZ11
2551      10061    BMSZ11
96        15049    BMSZ13
894       14329    BMSZ13
924       14051    BMSZ13
1173      14471    BMSZ13
1231      14179    BMSZ13
1613      14509    BMSZ13
1798      14169    BMSZ13
1802      14349    BMSZ13
1894      18019    BMSZ13
2378      14399    BMSZ13
2528      14189    BMSZ13
2703      14501    BMSZ13
3367      14499    BMSZ13
3369      14359    BMSZ13
3378      14351    BMSZ13
3743      14339    BMSZ13
3744      14331    BMSZ13
3926      15059    BMSZ13
4096      14041    BMSZ13
4399      14391    BMSZ13
4403      14341    BMSZ13
4729      14491    BMSZ13
4734      14211    BMSZ13
5133      14241    BMSZ13
91        15051    QTSZ14
95        15041    QTSZ14
285       15149    QTSZ14
318       15159    QTSZ14
425       15219    QTSZ14
1200      15079    QTSZ14
2285      15209    QTSZ14
3417      15169    QTSZ14
4390      15199    QTSZ14
463       03239    DTSZ11
760       03381    DTSZ11
764       03529    DTSZ11
879       03391    DTSZ11
2206      03059    DTSZ11
2284      03217    DTSZ11
2388      03219    DTSZ11
2484      03211    DTSZ11
3131      03569    DTSZ11
3132      03561    DTSZ11
4010      03539    DTSZ11
4996      03218    DTSZ11
581       10069    BMSZ05
2690      10039    BMSZ05
3154      10017    BMSZ05
3325      06011    BMSZ05
3466      10018    BMSZ05
3534      10049    BMSZ05
3985      10059    BMSZ05
150       14199    BMSZ12
907       14369    BMSZ12
1090      14209    BMSZ12
1649      14201    BMSZ12
2702      14219    BMSZ12
3559      14191    BMSZ12
15        10339    BMSZ02
73        10659    BMSZ02
1258      10091    BMSZ02
2090      10009    BMSZ02
3453      10331    BMSZ02
3997      10081    BMSZ02
4416      10651    BMSZ02
471       05519    OTSZ03
1102      05421    OTSZ03
1669      05131    OTSZ03
1764      05411    OTSZ03
2150      05241    OTSZ03
2244      05429    OTSZ03
2854      03041    OTSZ03
3135      05271    OTSZ03
3136      05259    OTSZ03
3328      05069    OTSZ03
3338      05019    OTSZ03
3687      05039    OTSZ03
4176      05239    OTSZ03
4424      05189    OTSZ03
1693      05319    DTSZ04
537       03021    DTSZ05
2652      03031    DTSZ05
2245      05049    OTSZ04
5029      05199    OTSZ04
1272      06051    BMSZ10
2513      10141    BMSZ10
4265      10149    BMSZ10
4311      10121    BMSZ10
4726      06071    BMSZ10
1163      03501    DTSZ12
4821      03509    DTSZ12
4822      03519    DTSZ12
4823      03511    DTSZ12
1074      10161    BMSZ04
1426      10079    BMSZ04
2314      10169    BMSZ04
4118      10379    BMSZ04
4987      10151    BMSZ04
4991      10129    BMSZ04
817       03011    DTSZ06
4825      03019    DTSZ06
1179      03341    MSSZ01
2436      03369    MSSZ01
4037      03331    MSSZ01
4627      03349    MSSZ01
4735      03371    MSSZ01
1394      06031    OTSZ01
1424      06039    OTSZ01
1999      06161    OTSZ01
2542      06069    OTSZ01
3884      06171    OTSZ01
5041      06049    OTSZ01
5082      05022    OTSZ01
851       05059    SRSZ03
1011      05029    SRSZ03
2246      05129    SRSZ03
2376      05009    SRSZ03
3848      04239    SRSZ03
542       10341    BMSZ08
659       10261    BMSZ08
1115      10181    BMSZ08
1608      10349    BMSZ08
1652      10241    BMSZ08
1782      10171    BMSZ08
1824      10179    BMSZ08
2099      10381    BMSZ08
2202      10089    BMSZ08
2621      10189    BMSZ08
3139      10199    BMSZ08
3209      10359    BMSZ08
3216      10351    BMSZ08
4435      10371    BMSZ08
492       10489    BMSZ03
1000      10451    BMSZ03
1276      10271    BMSZ03
2497      10099    BMSZ03
2619      10209    BMSZ03
3140      10201    BMSZ03
3141      10459    BMSZ03
3475      10481    BMSZ03
4828      10191    BMSZ03
132       10419    BMSZ07
142       10401    BMSZ07
302       10119    BMSZ07
802       10441    BMSZ07
866       10131    BMSZ07
920       10281    BMSZ07
991       10211    BMSZ07
1068      11519    BMSZ07
1097      10411    BMSZ07
1455      10139    BMSZ07
1681      10219    BMSZ07
1796      11539    BMSZ07
1833      10101    BMSZ07
2043      10291    BMSZ07
2339      10439    BMSZ07
2510      10111    BMSZ07
2639      11529    BMSZ07
3133      10429    BMSZ07
3134      10431    BMSZ07
3213      11019    BMSZ07
3451      10599    BMSZ07
4105      10109    BMSZ07
4487      10409    BMSZ07
5035      10449    BMSZ07
5159      10421    BMSZ07
476       10231    BMSZ09
797       10239    BMSZ09
832       06141    BMSZ09
1457      06081    BMSZ09
1493      10519    BMSZ09
2303      06131    BMSZ09
3189      10389    BMSZ09
3705      06149    BMSZ09
4458      10229    BMSZ09
5019      10221    BMSZ09
1045      06189    SRSZ02
1668      05023    SRSZ02
3029      04329    SRSZ02
3849      04222    SRSZ02
4303      04211    SRSZ02
42        16051    QTSZ13
76        16121    QTSZ13
264       16041    QTSZ13
451       16011    QTSZ13
663       16061    QTSZ13
690       16071    QTSZ13
864       16209    QTSZ13
1177      16029    QTSZ13
1274      15229    QTSZ13
1598      16039    QTSZ13
1699      16081    QTSZ13
1880      16069    QTSZ13
2162      15121    QTSZ13
2405      16249    QTSZ13
2409      16239    QTSZ13
2430      16219    QTSZ13
2558      16119    QTSZ13
2620      16059    QTSZ13
2669      16079    QTSZ13
2674      16019    QTSZ13
2676      16049    QTSZ13
2764      16111    QTSZ13
2887      16201    QTSZ13
3266      16101    QTSZ13
3373      15221    QTSZ13
3563      15071    QTSZ13
3607      15111    QTSZ13
3765      16031    QTSZ13
3821      16109    QTSZ13
4336      16021    QTSZ13
4413      15101    QTSZ13
4750      16089    QTSZ13
4818      16229    QTSZ13
5032      17299    QTSZ13
486       11021    QTSZ07
513       11511    QTSZ07
4279      11031    QTSZ07
56        15109    QTSZ12
420       15119    QTSZ12
597       15099    QTSZ12
940       15091    QTSZ12
1063      18011    QTSZ12
1160      18251    QTSZ12
1497      18269    QTSZ12
1767      18041    QTSZ12
2633      18131    QTSZ12
2682      15189    QTSZ12
3153      18249    QTSZ12
3420      15181    QTSZ12
3421      18241    QTSZ12
3430      15139    QTSZ12
4019      18281    QTSZ12
4294      18279    QTSZ12
4401      18271    QTSZ12
4422      18101    QTSZ12
4482      18261    QTSZ12
4691      18289    QTSZ12
4755      15129    QTSZ12
1746      10249    BMSZ06
2198      10269    BMSZ06
3142      10279    BMSZ06
3143      10329    BMSZ06
543       11459    QTSZ04
735       11171    QTSZ04
889       11161    QTSZ04
3715      11449    QTSZ04
3766      11441    QTSZ04
4132      11051    QTSZ04
4476      11181    QTSZ04
4614      11451    QTSZ04
4719      11041    QTSZ04
2490      40011    RCSZ06
2070      07529    RCSZ03
5108      07419    RCSZ03
88        18099    QTSZ08
368       18129    QTSZ08
696       18209    QTSZ08
791       18081    QTSZ08
1225      18109    QTSZ08
1255      18171    QTSZ08
1410      18179    QTSZ08
1731      18199    QTSZ08
1895      18189    QTSZ08
1993      18089    QTSZ08
2156      11191    QTSZ08
2231      18159    QTSZ08
2449      18059    QTSZ08
2791      18201    QTSZ08
3049      18211    QTSZ08
3117      18141    QTSZ08
3148      18021    QTSZ08
3348      18069    QTSZ08
3349      18061    QTSZ08
3841      18029    QTSZ08
4033      18121    QTSZ08
4067      18049    QTSZ08
4198      11369    QTSZ08
4364      18181    QTSZ08
4746      18151    QTSZ08
4900      18191    QTSZ08
4929      11361    QTSZ08
4975      18149    QTSZ08
4995      18051    QTSZ08
5094      18079    QTSZ08
35        80271    KLSZ05
135       90021    KLSZ05
173       80199    KLSZ05
310       80141    KLSZ05
844       90079    KLSZ05
1246      90039    KLSZ05
1267      90059    KLSZ05
1271      90029    KLSZ05
1667      90061    KLSZ05
2065      90011    KLSZ05
2522      90019    KLSZ05
2603      90051    KLSZ05
3014      91091    KLSZ05
3628      80189    KLSZ05
3950      80171    KLSZ05
3951      80179    KLSZ05
4034      91081    KLSZ05
4333      90031    KLSZ05
4391      80181    KLSZ05
4464      90069    KLSZ05
4887      80219    KLSZ05
5043      80191    KLSZ05
1372      11071    QTSZ03
1520      11061    QTSZ03
3606      11169    QTSZ03
4340      11439    QTSZ03
4415      11429    QTSZ03
1175      16099    QTSZ10
2091      19069    QTSZ10
2630      18119    QTSZ10
3247      19099    QTSZ10
3321      19081    QTSZ10
3980      19011    QTSZ10
4197      19071    QTSZ10
4526      19059    QTSZ10
4677      19079    QTSZ10
4834      17099    QTSZ10
4835      19089    QTSZ10
79        13031    TNSZ03
169       13041    TNSZ03
243       11221    TNSZ03
1042      11211    TNSZ03
1758      13021    TNSZ03
1840      11201    TNSZ03
1936      11089    TNSZ03
3465      13011    TNSZ03
3669      09141    TNSZ03
4699      13201    TNSZ03
4949      10471    TNSZ03
4956      10461    TNSZ03
117       17269    CLSZ08
337       17011    CLSZ08
852       17021    CLSZ08
922       17071    CLSZ08
1391      17041    CLSZ08
1741      17289    CLSZ08
2101      17279    CLSZ08
2916      17339    CLSZ08
2918      17329    CLSZ08
2921      17319    CLSZ08
4131      17031    CLSZ08
4211      17309    CLSZ08
4370      20291    CLSZ08
4495      17369    CLSZ08
4838      17081    CLSZ08
4840      17381    CLSZ08
5048      17359    CLSZ08
5155      17061    CLSZ08
3805      40021    NTSZ05
694       93039    BDSZ07
919       93159    BDSZ07
1040      93189    BDSZ07
1913      93151    BDSZ07
2275      93201    BDSZ07
2295      93161    BDSZ07
2614      93169    BDSZ07
2709      93149    BDSZ07
3295      93171    BDSZ07
3296      93179    BDSZ07
3931      93049    BDSZ07
4785      93199    BDSZ07
4855      93019    BDSZ07
5037      93029    BDSZ07
26        17049    CLSZ07
379       17389    CLSZ07
552       17039    CLSZ07
811       17129    CLSZ07
1012      17091    CLSZ07
1033      17131    CLSZ07
1360      17121    CLSZ07
1398      17019    CLSZ07
1470      16891    CLSZ07
1774      16151    CLSZ07
2269      17029    CLSZ07
2400      17191    CLSZ07
2984      17259    CLSZ07
4025      16991    CLSZ07
4135      16141    CLSZ07
4462      16131    CLSZ07
4911      17151    CLSZ07
267       24461    PNSZ05
538       24559    PNSZ05
801       24541    PNSZ05
1269      24431    PNSZ05
2100      24531    PNSZ05
2329      24549    PNSZ05
2428      24411    PNSZ05
2838      24381    PNSZ05
3187      24539    PNSZ05
3804      24451    PNSZ05
3901      24441    PNSZ05
3955      24401    PNSZ05
4272      24341    PNSZ05
4421      24351    PNSZ05
4507      24689    PNSZ05
4715      24669    PNSZ05
4806      24391    PNSZ05
4925      24679    PNSZ05
5130      24421    PNSZ05
106       29041    JESZ11
242       29089    JESZ11
534       29129    JESZ11
847       29081    JESZ11
1170      29071    JESZ11
1318      29091    JESZ11
1356      29069    JESZ11
1392      29019    JESZ11
1860      29101    JESZ11
2434      29139    JESZ11
2492      29099    JESZ11
2583      29049    JESZ11
2727      21059    JESZ11
3481      29119    JESZ11
3874      29109    JESZ11
3907      29149    JESZ11
3995      29059    JESZ11
4103      29011    JESZ11
4115      29111    JESZ11
4920      29121    JESZ11
2894      40191    NTSZ01
1586      80009    KLSZ04
3502      01349    KLSZ04
3948      01339    KLSZ04
3981      80029    KLSZ04
3982      80039    KLSZ04
4871      80049    KLSZ04
4886      80211    KLSZ04
4888      80111    KLSZ04
143       92169    MPSZ02
761       92129    MPSZ02
1187      92179    MPSZ02
1446      82129    MPSZ02
1512      82079    MPSZ02
1792      92111    MPSZ02
1850      92051    MPSZ02
2205      92171    MPSZ02
2250      92101    MPSZ02
2594      92189    MPSZ02
2654      92091    MPSZ02
3777      83301    MPSZ02
4000      82139    MPSZ02
4157      92121    MPSZ02
4350      92271    MPSZ02
5104      83311    MPSZ02
126       09011    ORSZ02
1093      09213    ORSZ02
1119      09169    ORSZ02
1885      09179    ORSZ02
2151      09212    ORSZ02
2529      09219    ORSZ02
3958      09048    ORSZ02
3972      09047    ORSZ02
4428      09023    ORSZ02
4204      40271    NTSZ06
3890      07539    RCSZ02
328       24379    PNSZ04
1445      23249    PNSZ04
1585      23239    PNSZ04
1624      24349    PNSZ04
1723      24359    PNSZ04
2386      23331    PNSZ04
2550      23311    PNSZ04
2605      23301    PNSZ04
3587      23229    PNSZ04
3811      24369    PNSZ04
3908      23291    PNSZ04
3959      23281    PNSZ04
4116      24339    PNSZ04
4205      23321    PNSZ04
4837      24389    PNSZ04
218       02151    DTSZ03
545       02061    DTSZ03
635       02171    DTSZ03
953       02149    DTSZ03
1082      02141    DTSZ03
1139      02101    DTSZ03
1140      80159    DTSZ03
1172      02169    DTSZ03
1259      02099    DTSZ03
1750      02119    DTSZ03
1797      02161    DTSZ03
1912      02159    DTSZ03
2251      02089    DTSZ03
3847      02051    DTSZ03
704       04142    MUSZ03
975       04143    MUSZ03
1018      07509    MUSZ03
1159      04179    MUSZ03
2018      04121    MUSZ03
4439      08041    MUSZ03
4583      04019    MUSZ03
4584      08069    MUSZ03
4701      04151    MUSZ03
244       13091    RVSZ04
24        04149    DTSZ02
518       04251    DTSZ02
608       02031    DTSZ02
1067      01629    DTSZ02
1213      80151    DTSZ02
1854      04167    DTSZ02
1984      04229    DTSZ02
2119      04168    DTSZ02
2711      01611    DTSZ02
3271      02029    DTSZ02
3533      01619    DTSZ02
3987      04159    DTSZ02
4066      04249    DTSZ02
4438      04111    DTSZ02
4741      02049    DTSZ02
4970      01519    DTSZ02
5091      02181    DTSZ02
5092      02111    DTSZ02
5093      02011    DTSZ02
5         11561    QTSZ06
119       11531    QTSZ06
167       11131    QTSZ06
861       11521    QTSZ06
1053      11141    QTSZ06
1302      11579    QTSZ06
1473      11151    QTSZ06
1817      11609    QTSZ06
2023      11589    QTSZ06
2268      11029    QTSZ06
3151      11059    QTSZ06
3929      11039    QTSZ06
4090      11599    QTSZ06
4983      11541    QTSZ06
4984      11551    QTSZ06
5026      11049    QTSZ06
1300      13159    RVSZ03
4262      13071    RVSZ03
4496      13081    RVSZ03
1158      17361    QTSZ15
1161      15151    QTSZ15
1948      16231    QTSZ15
2027      16211    QTSZ15
2281      15141    QTSZ15
2424      15191    QTSZ15
2443      17311    QTSZ15
2642      17351    QTSZ15
3435      15161    QTSZ15
3566      17291    QTSZ15
4513      17301    QTSZ15
4537      16241    QTSZ15
4656      15201    QTSZ15
4733      15211    QTSZ15
5013      16221    QTSZ15
435       08057    MUSZ01
3567      08079    MUSZ01
3794      08011    MUSZ01
4473      08058    MUSZ01
4676      08031    MUSZ01
289       01119    DTSZ01
427       01039    DTSZ01
459       01019    DTSZ01
559       01639    DTSZ01
898       01621    DTSZ01
1419      01139    DTSZ01
1781      01511    DTSZ01
2995      01113    DTSZ01
2996      01059    DTSZ01
3371      01631    DTSZ01
3924      01541    DTSZ01
4063      01029    DTSZ01
87        01013    RCSZ10
293       01112    RCSZ10
1335      01012    RCSZ10
2072      04029    RCSZ10
2274      07518    RCSZ10
2276      07517    RCSZ10
2504      07551    RCSZ10
2874      07569    RCSZ10
5149      07561    RCSZ10
622       09022    RVSZ02
3462      13199    RVSZ02
1214      92251    MPSZ04
1579      92191    MPSZ04
3828      92261    MPSZ04
4445      92289    MPSZ04
4681      92199    MPSZ04
4682      93181    MPSZ04
114       16171    QTSZ11
355       16181    QTSZ11
913       16009    QTSZ11
990       18221    QTSZ11
992       18239    QTSZ11
1168      18311    QTSZ11
1631      16169    QTSZ11
1753      18319    QTSZ11
1919      18301    QTSZ11
1986      16091    QTSZ11
2176      16161    QTSZ11
2335      16139    QTSZ11
2356      16189    QTSZ11
2532      18339    QTSZ11
3172      18309    QTSZ11
3232      16159    QTSZ11
3281      16199    QTSZ11
3283      16149    QTSZ11
3284      16191    QTSZ11
3518      15131    QTSZ11
3530      18329    QTSZ11
4250      18321    QTSZ11
4478      18331    QTSZ11
4859      18071    QTSZ11
5136      16179    QTSZ11
593       13179    RVSZ01
893       09121    RVSZ01
1467      09111    RVSZ01
2315      13169    RVSZ01
3467      13191    RVSZ01
4814      13189    RVSZ01
39        08137    ORSZ03
45        08111    ORSZ03
77        09059    ORSZ03
1251      09037    ORSZ03
2086      08138    ORSZ03
2374      09038    ORSZ03
3329      08121    ORSZ03
2272      07571    RCSZ09
4521      07531    RCSZ09
941       13121    TNSZ02
1155      13181    TNSZ02
1441      13171    TNSZ02
1785      13209    TNSZ02
2049      13069    TNSZ02
2304      13062    TNSZ02
3835      13049    TNSZ02
4184      13051    TNSZ02
4282      13039    TNSZ02
4486      13063    TNSZ02
4738      13141    TNSZ02
5134      13059    TNSZ02
5137      09131    TNSZ02
603       01129    RCSZ05
868       01521    RCSZ05
881       01231    RCSZ05
956       01229    RCSZ05
2258      01549    RCSZ05
4254      01559    RCSZ05
2021      07021    RCSZ08
4414      07011    RCSZ08
1342      07589    RCSZ04
1646      01121    RCSZ04
4266      01109    RCSZ04
181       01429    DTSZ13
2160      80169    DTSZ13
2286      80161    DTSZ13
2290      01529    DTSZ13
3689      01419    DTSZ13
84        10289    QTSZ05
491       11159    QTSZ05
807       10319    QTSZ05
885       11079    QTSZ05
910       11469    QTSZ05
963       10311    QTSZ05
1121      11499    QTSZ05
1521      11491    QTSZ05
1828      10309    QTSZ05
2407      10321    QTSZ05
2599      11139    QTSZ05
3376      11489    QTSZ05
3379      11471    QTSZ05
3778      11069    QTSZ05
4206      11149    QTSZ05
4457      10299    QTSZ05
4544      11481    QTSZ05
4597      10301    QTSZ05
4638      11479    QTSZ05
4789      10479    QTSZ05
4824      10469    QTSZ05
287       09191    ORSZ01
4552      09139    ORSZ01
34        92089    MPSZ03
36        82059    MPSZ03
217       92041    MPSZ03
524       92059    MPSZ03
582       92049    MPSZ03
2326      92069    MPSZ03
2976      92219    MPSZ03
2977      92229    MPSZ03
3021      92221    MPSZ03
3022      92211    MPSZ03
3023      92231    MPSZ03
3024      92079    MPSZ03
3025      92239    MPSZ03
3275      92181    MPSZ03
3681      92119    MPSZ03
3840      92099    MPSZ03
4059      92249    MPSZ03
4349      92241    MPSZ03
4492      92109    MPSZ03
170       23029    PNSZ01
332       24501    PNSZ01
461       23189    PNSZ01
530       24571    PNSZ01
621       23081    PNSZ01
639       23109    PNSZ01
755       24581    PNSZ01
1120      23141    PNSZ01
1208      23121    PNSZ01
1249      23019    PNSZ01
1393      23159    PNSZ01
1453      23169    PNSZ01
1495      24149    PNSZ01
1655      23509    PNSZ01
1742      24019    PNSZ01
1744      23501    PNSZ01
1760      23129    PNSZ01
1812      24041    PNSZ01
1960      24029    PNSZ01
2216      23149    PNSZ01
2223      23139    PNSZ01
2397      24599    PNSZ01
2548      24139    PNSZ01
2559      23091    PNSZ01
2582      23179    PNSZ01
3483      24489    PNSZ01
3491      23119    PNSZ01
3613      24129    PNSZ01
3638      23499    PNSZ01
3641      22161    PNSZ01
3783      23099    PNSZ01
3807      23101    PNSZ01
3976      23491    PNSZ01
4014      24009    PNSZ01
4018      23519    PNSZ01
4149      24159    PNSZ01
4484      23489    PNSZ01
4598      23379    PNSZ01
4603      23371    PNSZ01
4608      24499    PNSZ01
4923      23039    PNSZ01
4928      23111    PNSZ01
5058      23131    PNSZ01
110       60219    GLSZ01
210       70349    GLSZ01
400       60071    GLSZ01
740       70329    GLSZ01
1671      60061    GLSZ01
1686      70321    GLSZ01
2001      70311    GLSZ01
2063      70319    GLSZ01
2413      70341    GLSZ01
3360      70011    GLSZ01
3439      70021    GLSZ01
3572      70361    GLSZ01
3596      70359    GLSZ01
4392      70109    GLSZ01
4967      70031    GLSZ01
5040      70119    GLSZ01
2911      28041    JESZ07
3174      28309    JESZ07
3529      28229    JESZ07
3556      20059    JESZ07
82        21319    BLSZ01
415       21469    BLSZ01
636       21181    BLSZ01
691       22219    BLSZ01
809       22019    BLSZ01
1165      21479    BLSZ01
1319      21311    BLSZ01
1378      21171    BLSZ01
1466      22039    BLSZ01
1956      22229    BLSZ01
2840      21461    BLSZ01
2841      21489    BLSZ01
3497      22169    BLSZ01
3891      21329    BLSZ01
3971      22029    BLSZ01
4210      21481    BLSZ01
4227      21549    BLSZ01
4233      21321    BLSZ01
4257      21499    BLSZ01
4506      21471    BLSZ01
4922      21491    BLSZ01
196       11349    BTSZ06
899       42129    BTSZ06
1315      41041    BTSZ06
1401      41071    BTSZ06
1889      42139    BTSZ06
2575      41061    BTSZ06
3252      41111    BTSZ06
4030      41051    BTSZ06
4078      41031    BTSZ06
4665      41081    BTSZ06
108       84011    BDSZ03
193       84369    BDSZ03
259       84021    BDSZ03
487       83321    BDSZ03
833       84561    BDSZ03
834       84551    BDSZ03
1028      83109    BDSZ03
1656      83341    BDSZ03
1680      84541    BDSZ03
1716      83331    BDSZ03
1793      84559    BDSZ03
1869      84549    BDSZ03
2097      84579    BDSZ03
2127      84641    BDSZ03
2327      84649    BDSZ03
2367      83361    BDSZ03
2508      83081    BDSZ03
2651      83011    BDSZ03
2930      84589    BDSZ03
2931      84581    BDSZ03
3106      84571    BDSZ03
3149      83351    BDSZ03
3238      83063    BDSZ03
3243      83062    BDSZ03
3249      83031    BDSZ03
4335      83381    BDSZ03
4447      83329    BDSZ03
4732      84301    BDSZ03
4841      83119    BDSZ03
4891      84569    BDSZ03
4901      83371    BDSZ03
327       41129    NVSZ04
943       40231    NVSZ04
1024      41019    NVSZ04
1171      41029    NVSZ04
2010      41139    NVSZ04
4091      40099    NVSZ04
837       17439    CLSZ02
1019      17409    CLSZ02
1469      12209    CLSZ02
1615      17419    CLSZ02
2352      12071    CLSZ02
2579      17399    CLSZ02
3661      12061    CLSZ02
4740      17429    CLSZ02
568       70191    GLSZ02
1004      70151    GLSZ02
1071      70171    GLSZ02
1733      70181    GLSZ02
1856      70261    GLSZ02
1974      70271    GLSZ02
2299      70381    GLSZ02
2500      70221    GLSZ02
3353      70029    GLSZ02
3355      70241    GLSZ02
3359      70019    GLSZ02
3362      70211    GLSZ02
3427      70149    GLSZ02
4248      70251    GLSZ02
4642      70129    GLSZ02
4913      70039    GLSZ02
5030      70139    GLSZ02
5099      70201    GLSZ02
5100      70379    GLSZ02
5101      70371    GLSZ02
5111      70161    GLSZ02
5112      70231    GLSZ02
1091      52319    TPSZ07
2925      52331    TPSZ07
4902      52081    TPSZ07
21        84409    BDSZ04
130       85101    BDSZ04
336       84321    BDSZ04
480       84411    BDSZ04
496       84329    BDSZ04
573       84371    BDSZ04
654       84211    BDSZ04
712       85061    BDSZ04
746       85081    BDSZ04
823       84031    BDSZ04
880       84361    BDSZ04
930       85059    BDSZ04
984       84311    BDSZ04
1243      84241    BDSZ04
1264      84239    BDSZ04
1309      84191    BDSZ04
1323      84339    BDSZ04
1399      84259    BDSZ04
1478      84429    BDSZ04
1494      84251    BDSZ04
1505      84449    BDSZ04
1739      84529    BDSZ04
1947      84381    BDSZ04
1983      84281    BDSZ04
2046      85069    BDSZ04
2093      84231    BDSZ04
2157      84391    BDSZ04
2190      84269    BDSZ04
2192      84379    BDSZ04
2228      84051    BDSZ04
2300      84219    BDSZ04
2474      84349    BDSZ04
2547      84421    BDSZ04
3026      84351    BDSZ04
3027      84359    BDSZ04
3575      84199    BDSZ04
3625      84061    BDSZ04
3651      85091    BDSZ04
3671      84319    BDSZ04
3754      84008    BDSZ04
3755      84009    BDSZ04
3771      85051    BDSZ04
3820      84261    BDSZ04
3844      84091    BDSZ04
4098      84041    BDSZ04
4244      84401    BDSZ04
4423      84341    BDSZ04
4623      84249    BDSZ04
4651      84331    BDSZ04
4704      84289    BDSZ04
4728      84309    BDSZ04
4851      84419    BDSZ04
4890      84229    BDSZ04
4972      84521    BDSZ04
4973      84221    BDSZ04
5089      85089    BDSZ04
74        52149    TPSZ02
92        51029    TPSZ02
410       52251    TPSZ02
667       51049    TPSZ02
689       52501    TPSZ02
732       52199    TPSZ02
845       52261    TPSZ02
1307      52181    TPSZ02
1322      52071    TPSZ02
1330      51039    TPSZ02
1404      52509    TPSZ02
1463      52191    TPSZ02
1842      52139    TPSZ02
2350      52321    TPSZ02
3276      52231    TPSZ02
3748      52008    TPSZ02
3749      52009    TPSZ02
3797      52189    TPSZ02
3836      51019    TPSZ02
4290      52131    TPSZ02
4759      52239    TPSZ02
147       28061    JESZ06
1003      28051    JESZ06
1288      28449    JESZ06
1389      28239    JESZ06
2076      28201    JESZ06
2686      28009    JESZ06
2913      28059    JESZ06
3030      28211    JESZ06
3183      28301    JESZ06
4341      28431    JESZ06
4721      28199    JESZ06
4860      28249    JESZ06
344       12099    BTSZ03
406       12079    BTSZ03
976       42031    BTSZ03
1207      11331    BTSZ03
1279      11301    BTSZ03
1462      11321    BTSZ03
1729      12039    BTSZ03
2134      11311    BTSZ03
2193      12109    BTSZ03
2211      12119    BTSZ03
2282      12049    BTSZ03
2471      42061    BTSZ03
2664      42021    BTSZ03
3326      11299    BTSZ03
3406      12029    BTSZ03
3662      12069    BTSZ03
3788      42051    BTSZ03
4114      42149    BTSZ03
4235      42041    BTSZ03
4287      12089    BTSZ03
4663      42011    BTSZ03
4713      11341    BTSZ03
4817      12059    BTSZ03
5018      42131    BTSZ03
70        71101    GLSZ03
90        70071    GLSZ03
122       71169    GLSZ03
224       71111    GLSZ03
225       71149    GLSZ03
387       71089    GLSZ03
521       70079    GLSZ03
616       70091    GLSZ03
921       70089    GLSZ03
951       71079    GLSZ03
1306      71099    GLSZ03
1375      71141    GLSZ03
1412      72011    GLSZ03
1692      70081    GLSZ03
1808      71151    GLSZ03
1975      70279    GLSZ03
2113      70269    GLSZ03
2255      71161    GLSZ03
2380      70099    GLSZ03
2842      71139    GLSZ03
3011      71179    GLSZ03
3031      70409    GLSZ03
3032      70401    GLSZ03
3433      70259    GLSZ03
3554      71131    GLSZ03
3621      71159    GLSZ03
3781      71029    GLSZ03
3784      71129    GLSZ03
4231      71121    GLSZ03
4792      71221    GLSZ03
4793      71119    GLSZ03
4794      71229    GLSZ03
4795      71219    GLSZ03
4797      71211    GLSZ03
4798      71201    GLSZ03
4800      71209    GLSZ03
4801      71109    GLSZ03
413       70111    TPSZ11
699       70041    TPSZ11
923       70051    TPSZ11
1659      61029    TPSZ11
1784      60211    TPSZ11
2243      60269    TPSZ11
2516      60209    TPSZ11
3307      61111    TPSZ11
3867      70061    TPSZ11
4325      61019    TPSZ11
5066      61119    TPSZ11
5086      70101    TPSZ11
115       61101    TPSZ09
525       60201    TPSZ09
1048      61089    TPSZ09
1078      61079    TPSZ09
1969      61009    TPSZ09
2079      60261    TPSZ09
2242      61069    TPSZ09
2521      61099    TPSZ09
3517      60081    TPSZ09
3772      61011    TPSZ09
4386      61061    TPSZ09
13        25099    TSSZ03
58        25379    TSSZ03
85        25509    TSSZ03
203       25119    TSSZ03
575       25161    TSSZ03
632       25091    TSSZ03
738       25079    TSSZ03
967       25171    TSSZ03
1081      25501    TSSZ03
1219      25101    TSSZ03
1241      25071    TSSZ03
1331      25321    TSSZ03
1382      25069    TSSZ03
1435      25061    TSSZ03
1527      24529    TSSZ03
1679      25369    TSSZ03
1804      25389    TSSZ03
1820      25189    TSSZ03
1988      25169    TSSZ03
2040      25191    TSSZ03
2088      25519    TSSZ03
2316      25239    TSSZ03
2341      25339    TSSZ03
2729      24701    TSSZ03
2731      24711    TSSZ03
2733      25539    TSSZ03
2734      25531    TSSZ03
2735      25541    TSSZ03
2736      25549    TSSZ03
2737      25551    TSSZ03
2738      25559    TSSZ03
2743      25589    TSSZ03
3093      25811    TSSZ03
3162      24519    TSSZ03
3419      25819    TSSZ03
3552      25371    TSSZ03
3639      25361    TSSZ03
3789      25329    TSSZ03
3825      25151    TSSZ03
3878      25199    TSSZ03
3879      25359    TSSZ03
3973      25341    TSSZ03
4049      25229    TSSZ03
4150      25331    TSSZ03
4226      25181    TSSZ03
4234      25351    TSSZ03
4331      25179    TSSZ03
4363      25129    TSSZ03
4407      25121    TSSZ03
4753      25219    TSSZ03
4833      25381    TSSZ03
4921      25201    TSSZ03
4935      25349    TSSZ03
5039      25511    TSSZ03
5062      25109    TSSZ03
5073      25111    TSSZ03
5157      25209    TSSZ03
25        52429    TPSZ06
261       52389    TPSZ06
301       52439    TPSZ06
401       52391    TPSZ06
586       52481    TPSZ06
1447      52399    TPSZ06
1978      52341    TPSZ06
2577      52489    TPSZ06
5154      52311    TPSZ06
191       52269    TPSZ04
472       52281    TPSZ04
747       52289    TPSZ04
914       52291    TPSZ04
1518      52349    TPSZ04
2174      52259    TPSZ04
2259      52299    TPSZ04
2920      52309    TPSZ04
2923      52301    TPSZ04
2924      52339    TPSZ04
3304      52359    TPSZ04
3711      52329    TPSZ04
4542      52279    TPSZ04
11        23151    JWSZ06
208       22281    JWSZ06
297       21331    JWSZ06
418       21351    JWSZ06
482       22479    JWSZ06
742       23051    JWSZ06
966       22289    JWSZ06
1429      23061    JWSZ06
1566      22549    JWSZ06
1650      22559    JWSZ06
1710      23171    JWSZ06
1720      21341    JWSZ06
2000      22181    JWSZ06
2139      22309    JWSZ06
2457      22329    JWSZ06
2648      22609    JWSZ06
3165      23071    JWSZ06
3488      22439    JWSZ06
3643      22319    JWSZ06
3644      22189    JWSZ06
3646      23161    JWSZ06
3780      23181    JWSZ06
3787      22191    JWSZ06
3790      22179    JWSZ06
3883      22199    JWSZ06
3887      22299    JWSZ06
3957      22171    JWSZ06
3992      22221    JWSZ06
4189      23481    JWSZ06
4232      22271    JWSZ06
4490      22569    JWSZ06
4525      22431    JWSZ06
5068      23041    JWSZ06
5151      22571    JWSZ06
628       23049    JWSZ07
1135      23089    JWSZ07
2325      23079    JWSZ07
2545      23059    JWSZ07
3989      23069    JWSZ07
2013      40019    RCSZ01
4024      50251    RCSZ01
4562      07031    RCSZ01
5078      07111    RCSZ01
175       40031    NTSZ03
3482      40189    NTSZ03
3678      40179    NTSZ03
3803      40181    NTSZ03
3903      40041    NTSZ03
388       21079    JESZ10
464       21099    JESZ10
564       21139    JESZ10
1752      21119    JESZ10
1838      21109    JESZ10
1901      21129    JESZ10
2225      21069    JESZ10
4040      21089    JESZ10
1         22069    BLSZ03
394       22399    BLSZ03
682       22079    BLSZ03
763       22409    BLSZ03
1029      22099    BLSZ03
1461      22049    BLSZ03
1542      23451    BLSZ03
1549      23469    BLSZ03
1614      22421    BLSZ03
1711      22331    BLSZ03
2249      22081    BLSZ03
2659      22089    BLSZ03
3616      22059    BLSZ03
3798      23461    BLSZ03
4538      22429    BLSZ03
7         23389    BLSZ04
391       22401    BLSZ04
452       23381    BLSZ04
640       22091    BLSZ04
652       23411    BLSZ04
739       23399    BLSZ04
1005      23439    BLSZ04
1644      23391    BLSZ04
2188      23401    BLSZ04
3489      23429    BLSZ04
3796      23259    BLSZ04
3882      23419    BLSZ04
3904      23269    BLSZ04
4187      23431    BLSZ04
4451      22391    BLSZ04
4491      23409    BLSZ04
4847      23421    BLSZ04
4895      23279    BLSZ04
741       12129    QTSZ01
3124      11351    QTSZ01
3125      11199    QTSZ01
3126      11009    QTSZ01
3665      11009    QTSZ01
4060      19019    QTSZ01
4222      11359    QTSZ01
5042      12121    QTSZ01
497       07231    KLSZ06
870       07329    KLSZ06
1687      07319    KLSZ06
1721      07241    KLSZ06
1961      07221    KLSZ06
2700      07351    KLSZ06
2950      01319    KLSZ06
3259      07211    KLSZ06
3396      01311    KLSZ06
3949      07371    KLSZ06
3956      07361    KLSZ06
4318      50259    KLSZ06
4347      07331    KLSZ06
1025      40171    NTSZ02
2059      40051    NTSZ02
2895      40199    NTSZ02
342       20319    CLSZ09
493       20341    CLSZ09
945       20329    CLSZ09
2425      20331    CLSZ09
2915      20281    CLSZ09
2917      17331    CLSZ09
2919      17321    CLSZ09
2958      20131    CLSZ09
3808      20309    CLSZ09
199       19029    QTSZ09
358       19021    QTSZ09
455       19061    QTSZ09
814       19091    QTSZ09
2717      19039    QTSZ09
2718      19031    QTSZ09
3217      19041    QTSZ09
3221      19049    QTSZ09
3548      19051    QTSZ09
3741      17119    QTSZ09
3742      17109    QTSZ09
190       17079    CLSZ06
468       20011    CLSZ06
563       17051    CLSZ06
905       17139    CLSZ06
982       17141    CLSZ06
998       17009    CLSZ06
1682      17149    CLSZ06
2235      20019    CLSZ06
2453      17181    CLSZ06
2482      17239    CLSZ06
2986      17251    CLSZ06
3048      17171    CLSZ06
3405      17161    CLSZ06
3896      17069    CLSZ06
4328      20299    CLSZ06
16        50011    KLSZ07
730       50301    KLSZ07
1188      50239    KLSZ07
1263      50079    KLSZ07
3268      50321    KLSZ07
3484      40101    KLSZ07
3683      50249    KLSZ07
3816      40109    KLSZ07
3962      40279    KLSZ07
3970      50279    KLSZ07
4086      50261    KLSZ07
4228      50071    KLSZ07
4472      50019    KLSZ07
4678      50089    KLSZ07
4679      50081    KLSZ07
4707      50351    KLSZ07
188       80101    KLSZ03
194       80051    KLSZ03
275       80031    KLSZ03
3940      80319    KLSZ03
3942      80309    KLSZ03
3944      80311    KLSZ03
4872      80109    KLSZ03
4958      80301    KLSZ03
220       60059    KLSZ08
429       80011    KLSZ08
2865      60019    KLSZ08
2867      07359    KLSZ08
2868      60011    KLSZ08
3230      07369    KLSZ08
3390      60051    KLSZ08
3507      60099    KLSZ08
3935      60029    KLSZ08
4255      60119    KLSZ08
5010      60021    KLSZ08
5087      07379    KLSZ08
80        12199    BTSZ04
118       11291    BTSZ04
620       12141    BTSZ04
958       12041    BTSZ04
1122      11271    BTSZ04
1508      12051    BTSZ04
1949      12189    BTSZ04
2128      12031    BTSZ04
2361      11281    BTSZ04
2647      12139    BTSZ04
3739      12111    BTSZ04
3809      12179    BTSZ04
4224      12211    BTSZ04
4354      12151    BTSZ04
4510      12149    BTSZ04
4807      12169    BTSZ04
5051      12021    BTSZ04
5054      12131    BTSZ04
49        11101    BTSZ08
1903      11111    BTSZ08
1942      41101    BTSZ08
4264      11239    BTSZ08
4712      11091    BTSZ08
964       40219    TNSZ01
2466      40091    TNSZ01
2523      40071    TNSZ01
2611      40211    TNSZ01
3458      40229    TNSZ01
3459      40081    TNSZ01
3461      13019    TNSZ01
3463      40221    TNSZ01
3603      40111    TNSZ01
3800      09159    TNSZ01
4195      40209    TNSZ01
4568      09149    TNSZ01
4917      40201    TNSZ01
2922      20289    CLSZ05
2957      20139    CLSZ05
3182      20021    CLSZ05
4133      20031    CLSZ05
67        94049    BDSZ08
215       94029    BDSZ08
260       94009    BDSZ08
959       94089    BDSZ08
1485      94019    BDSZ08
1545      93131    BDSZ08
1765      94099    BDSZ08
1923      94069    BDSZ08
2064      94059    BDSZ08
4383      94079    BDSZ08
4667      94039    BDSZ08
661       23211    PNSZ03
672       23199    PNSZ03
1058      23219    PNSZ03
1141      23251    PNSZ03
1945      23479    PNSZ03
2663      23191    PNSZ03
3003      22141    PNSZ03
3479      23261    PNSZ03
3536      23449    PNSZ03
3846      23011    PNSZ03
3855      23471    PNSZ03
3881      23369    PNSZ03
3888      23031    PNSZ03
3963      23349    PNSZ03
3975      23359    PNSZ03
4229      23241    PNSZ03
4285      23271    PNSZ03
4716      22151    PNSZ03
4810      23021    PNSZ03
4819      23201    PNSZ03
4820      23209    PNSZ03
93        24011    PNSZ02
386       24249    PNSZ02
422       24209    PNSZ02
453       24089    PNSZ02
509       24521    PNSZ02
584       24631    PNSZ02
1112      24229    PNSZ02
1128      24169    PNSZ02
1296      24681    PNSZ02
1704      24269    PNSZ02
1955      24021    PNSZ02
2201      24279    PNSZ02
2520      24259    PNSZ02
2541      24189    PNSZ02
2839      24671    PNSZ02
3485      24289    PNSZ02
3493      24651    PNSZ02
3540      23441    PNSZ02
3636      24299    PNSZ02
3785      24511    PNSZ02
3792      23221    PNSZ02
3815      24301    PNSZ02
3960      23231    PNSZ02
3979      24219    PNSZ02
4085      24239    PNSZ02
4144      24179    PNSZ02
4175      24639    PNSZ02
4196      23361    PNSZ02
4200      23341    PNSZ02
4209      24691    PNSZ02
4230      24641    PNSZ02
4238      24199    PNSZ02
4483      24661    PNSZ02
4530      24331    PNSZ02
4649      23351    PNSZ02
268       41109    TNSZ04
426       11119    TNSZ04
665       41119    TNSZ04
979       13029    TNSZ04
2083      11229    TNSZ04
2420      11219    TNSZ04
2671      41011    TNSZ04
3019      41021    TNSZ04
3501      11099    TNSZ04
4796      11209    TNSZ04
5106      11109    TNSZ04
535       50121    NVSZ02
887       50069    NVSZ02
1038      40059    NVSZ02
1260      50038    NVSZ02
1436      40121    NVSZ02
1570      50111    NVSZ02
1997      50029    NVSZ02
2200      40129    NVSZ02
2554      50129    NVSZ02
3399      50061    NVSZ02
4684      40039    NVSZ02
4836      50119    NVSZ02
4864      50031    NVSZ02
4919      40029    NVSZ02
4930      40049    NVSZ02
5083      50021    NVSZ02
333       22041    BLSZ02
623       21141    BLSZ02
692       21301    BLSZ02
799       22061    BLSZ02
1625      21131    BLSZ02
1666      21309    BLSZ02
1787      21151    BLSZ02
2011      22011    BLSZ02
2213      21291    BLSZ02
2287      22071    BLSZ02
2451      21299    BLSZ02
3004      22149    BLSZ02
3354      22031    BLSZ02
3395      21121    BLSZ02
3697      22159    BLSZ02
4065      21041    BLSZ02
4971      21111    BLSZ02
5124      22021    BLSZ02
5132      22051    BLSZ02
22        84029    BDSZ05
31        83139    BDSZ05
63        93089    BDSZ05
185       83029    BDSZ05
299       93059    BDSZ05
376       83099    BDSZ05
428       92081    BDSZ05
441       83191    BDSZ05
442       93051    BDSZ05
465       93071    BDSZ05
479       84159    BDSZ05
510       83239    BDSZ05
527       83319    BDSZ05
569       83251    BDSZ05
607       83269    BDSZ05
670       93091    BDSZ05
737       93139    BDSZ05
819       93129    BDSZ05
854       93079    BDSZ05
855       92131    BDSZ05
859       92139    BDSZ05
884       92151    BDSZ05
906       93031    BDSZ05
908       83261    BDSZ05
927       84139    BDSZ05
988       83201    BDSZ05
1020      83299    BDSZ05
1080      83199    BDSZ05
1088      83231    BDSZ05
1147      83049    BDSZ05
1228      93101    BDSZ05
1430      83169    BDSZ05
1434      83271    BDSZ05
1484      93041    BDSZ05
1559      83171    BDSZ05
1712      83059    BDSZ05
1799      93109    BDSZ05
1823      83149    BDSZ05
1916      84131    BDSZ05
1932      83079    BDSZ05
1952      92061    BDSZ05
1967      83159    BDSZ05
1980      84019    BDSZ05
2009      93111    BDSZ05
2037      84129    BDSZ05
2045      83281    BDSZ05
2071      92149    BDSZ05
2194      84121    BDSZ05
2230      93119    BDSZ05
2370      83189    BDSZ05
2384      92159    BDSZ05
2479      83129    BDSZ05
2499      83131    BDSZ05
2527      83209    BDSZ05
2596      83229    BDSZ05
2793      83279    BDSZ05
2942      84169    BDSZ05
3020      92071    BDSZ05
3097      92201    BDSZ05
3228      93121    BDSZ05
3508      92301    BDSZ05
3583      92279    BDSZ05
3593      93021    BDSZ05
3611      93069    BDSZ05
3996      83309    BDSZ05
4099      83141    BDSZ05
4122      93011    BDSZ05
4146      92309    BDSZ05
4163      83151    BDSZ05
4289      83181    BDSZ05
4443      92209    BDSZ05
4471      92141    BDSZ05
4748      83121    BDSZ05
4790      93061    BDSZ05
4804      83219    BDSZ05
4853      83179    BDSZ05
4877      84039    BDSZ05
4904      93099    BDSZ05
5004      93081    BDSZ05
5007      83249    BDSZ05
673       17241    CLSZ04
871       17371    CLSZ04
978       17249    CLSZ04
1109      17219    CLSZ04
1304      20109    CLSZ04
2028      17379    CLSZ04
2345      17159    CLSZ04
2406      17201    CLSZ04
2980      17179    CLSZ04
3404      17169    CLSZ04
3407      17189    CLSZ04
3408      17229    CLSZ04
3740      17101    CLSZ04
4669      17221    CLSZ04
4696      17111    CLSZ04
5142      17211    CLSZ04
1023      11081    BTSZ07
1142      11329    BTSZ07
2166      11279    BTSZ07
2310      11339    BTSZ07
2368      11309    BTSZ07
3164      11289    BTSZ07
3424      11231    BTSZ07
3445      11319    BTSZ07
3522      11269    BTSZ07
3969      11419    BTSZ07
398       82121    GLSZ05
514       82099    GLSZ05
664       82009    GLSZ05
751       82221    GLSZ05
773       81101    GLSZ05
794       82141    GLSZ05
1036      81131    GLSZ05
1050      82091    GLSZ05
1065      82151    GLSZ05
1118      82109    GLSZ05
1509      82089    GLSZ05
2035      82221    GLSZ05
2320      82149    GLSZ05
2445      83291    GLSZ05
2456      82081    GLSZ05
2505      82032    GLSZ05
2645      82029    GLSZ05
2762      82111    GLSZ05
3434      82011    GLSZ05
3505      81111    GLSZ05
3608      82229    GLSZ05
3675      82171    GLSZ05
3830      82231    GLSZ05
3900      82131    GLSZ05
4047      81141    GLSZ05
4284      82181    GLSZ05
4388      82033    GLSZ05
4561      82061    GLSZ05
4563      83101    GLSZ05
4636      82049    GLSZ05
4652      82119    GLSZ05
4873      82069    GLSZ05
4932      81191    GLSZ05
5012      83111    GLSZ05
5021      82159    GLSZ05
5088      82179    GLSZ05
47        20251    JESZ09
298       20061    JESZ09
389       20129    JESZ09
454       29039    JESZ09
473       20121    JESZ09
580       20211    JESZ09
688       29029    JESZ09
715       20189    JESZ09
777       20169    JESZ09
872       20161    JESZ09
1428      29051    JESZ09
1702      20159    JESZ09
1800      20081    JESZ09
1853      29159    JESZ09
2411      20151    JESZ09
2498      20191    JESZ09
2933      20149    JESZ09
2934      20141    JESZ09
3210      20201    JESZ09
3558      20249    JESZ09
3670      20179    JESZ09
3978      20051    JESZ09
4219      20209    JESZ09
4236      20219    JESZ09
4276      20239    JESZ09
4515      20261    JESZ09
4523      20269    JESZ09
4705      20171    JESZ09
4777      20199    JESZ09
4899      20231    JESZ09
4933      20181    JESZ09
4957      20259    JESZ09
599       21149    JESZ08
1691      29031    JESZ08
2017      29021    JESZ08
2226      21011    JESZ08
2442      21071    JESZ08
2480      21021    JESZ08
2728      21051    JESZ08
3562      20241    JESZ08
3717      21159    JESZ08
4064      21049    JESZ08
371       60039    KLSZ02
445       60031    KLSZ02
793       60229    KLSZ02
2590      60069    KLSZ02
2612      60159    KLSZ02
2668      60179    KLSZ02
3382      60079    KLSZ02
3941      80291    KLSZ02
3945      80299    KLSZ02
5014      60221    KLSZ02
683       20101    CLSZ03
3515      20039    CLSZ03
3620      20029    CLSZ03
3791      28031    CLSZ03
3886      28021    CLSZ03
4141      17059    CLSZ03
4202      28011    CLSZ03
187       51099    NVSZ03
916       50051    NVSZ03
1532      51011    NVSZ03
2131      51109    NVSZ03
2719      40079    NVSZ03
3460      40239    NVSZ03
3464      40089    NVSZ03
4201      40119    NVSZ03
4449      40249    NVSZ03
4549      40069    NVSZ03
5044      50041    NVSZ03
431       84661    BDSZ06
565       85031    BDSZ06
778       85021    BDSZ06
789       94011    BDSZ06
825       84111    BDSZ06
874       84679    BDSZ06
957       85109    BDSZ06
1210      94061    BDSZ06
1273      84119    BDSZ06
1365      84071    BDSZ06
1418      84079    BDSZ06
1468      84681    BDSZ06
1492      84161    BDSZ06
1548      84069    BDSZ06
1719      85049    BDSZ06
1883      84089    BDSZ06
1892      84691    BDSZ06
2141      85039    BDSZ06
2167      85019    BDSZ06
2358      84149    BDSZ06
2369      84151    BDSZ06
2383      84049    BDSZ06
2616      84671    BDSZ06
3578      84141    BDSZ06
3650      85099    BDSZ06
3703      94051    BDSZ06
3930      85029    BDSZ06
4127      85041    BDSZ06
4128      94021    BDSZ06
4185      84081    BDSZ06
4425      84669    BDSZ06
4559      84101    BDSZ06
4560      84109    BDSZ06
4668      94031    BDSZ06
4843      94071    BDSZ06
4908      94041    BDSZ06
444       60121    KLSZ01
962       50331    KLSZ01
1388      60089    KLSZ01
1582      60181    KLSZ01
1837      60141    KLSZ01
2005      60139    KLSZ01
2533      07249    KLSZ01
2604      50231    KLSZ01
3202      60241    KLSZ01
3206      60199    KLSZ01
3401      60101    KLSZ01
4155      60161    KLSZ01
4270      60191    KLSZ01
4314      60249    KLSZ01
4405      50349    KLSZ01
4558      50241    KLSZ01
5001      60251    KLSZ01
52        50059    NVSZ01
284       50991    NVSZ01
317       50211    NVSZ01
393       50169    NVSZ01
434       52089    NVSZ01
506       52411    NVSZ01
577       52409    NVSZ01
1218      50049    NVSZ01
1343      52129    NVSZ01
1397      52499    NVSZ01
1498      50159    NVSZ01
1654      50209    NVSZ01
1664      50201    NVSZ01
1788      52079    NVSZ01
1858      52099    NVSZ01
1962      50171    NVSZ01
1994      50037    NVSZ01
2036      50161    NVSZ01
2107      52471    NVSZ01
2196      50199    NVSZ01
2337      50179    NVSZ01
2387      52419    NVSZ01
2772      52049    NVSZ01
2773      52059    NVSZ01
3215      52479    NVSZ01
3506      52401    NVSZ01
3829      52451    NVSZ01
4326      50191    NVSZ01
4630      50189    NVSZ01
4672      50229    NVSZ01
4673      50221    NVSZ01
5153      52109    NVSZ01
136       25391    TSSZ02
308       25411    TSSZ02
749       25429    TSSZ02
813       25479    TSSZ02
840       25259    TSSZ02
915       25471    TSSZ02
1502      26251    TSSZ02
1911      25459    TSSZ02
2172      25469    TSSZ02
2293      25439    TSSZ02
2487      26209    TSSZ02
2525      25421    TSSZ02
2535      25451    TSSZ02
2629      26261    TSSZ02
2769      25689    TSSZ02
2770      25681    TSSZ02
3343      25499    TSSZ02
3550      26201    TSSZ02
3614      25461    TSSZ02
3894      25491    TSSZ02
4048      25249    TSSZ02
4188      25431    TSSZ02
4239      26241    TSSZ02
4460      25449    TSSZ02
4643      25441    TSSZ02
5057      25009    TSSZ02
5105      25419    TSSZ02
329       66389    SGSZ06
507       66381    SGSZ06
627       66371    SGSZ06
860       66401    SGSZ06
1205      66049    SGSZ06
1290      63149    SGSZ06
1563      66009    SGSZ06
1855      63369    SGSZ06
2112      63161    SGSZ06
2278      66361    SGSZ06
2302      66369    SGSZ06
2351      66359    SGSZ06
2929      62141    SGSZ06
3214      66351    SGSZ06
3280      62121    SGSZ06
3561      66411    SGSZ06
3582      63141    SGSZ06
3624      66039    SGSZ06
3827      66391    SGSZ06
3831      66059    SGSZ06
4104      66419    SGSZ06
4181      62131    SGSZ06
4655      63151    SGSZ06
4717      66379    SGSZ06
177       53211    BSSZ03
304       53229    BSSZ03
311       53409    BSSZ03
345       53289    BSSZ03
367       54109    BSSZ03
519       53271    BSSZ03
551       53401    BSSZ03
572       54531    BSSZ03
785       53269    BSSZ03
911       53261    BSSZ03
1060      53009    BSSZ03
1353      53221    BSSZ03
1553      52021    BSSZ03
1891      53419    BSSZ03
2080      53251    BSSZ03
2163      53259    BSSZ03
3291      52031    BSSZ03
3294      52061    BSSZ03
3302      52051    BSSZ03
3510      53279    BSSZ03
3688      53231    BSSZ03
4140      53241    BSSZ03
4142      53281    BSSZ03
46        75201    TMSZ03
209       75169    TMSZ03
390       75061    TMSZ03
490       75229    TMSZ03
645       75069    TMSZ03
651       75101    TMSZ03
983       75031    TMSZ03
985       75021    TMSZ03
994       75151    TMSZ03
1031      75209    TMSZ03
1043      75339    TMSZ03
1055      75379    TMSZ03
1152      75039    TMSZ03
1261      75221    TMSZ03
1332      75241    TMSZ03
1376      75131    TMSZ03
1413      75109    TMSZ03
1414      75081    TMSZ03
1522      75159    TMSZ03
1573      75231    TMSZ03
1577      75089    TMSZ03
1726      75139    TMSZ03
1777      75329    TMSZ03
1832      75239    TMSZ03
2006      75261    TMSZ03
2032      75161    TMSZ03
2047      75219    TMSZ03
2105      75141    TMSZ03
2447      75071    TMSZ03
2567      75111    TMSZ03
2870      75259    TMSZ03
2989      75419    TMSZ03
2991      75409    TMSZ03
3045      76049    TMSZ03
3262      75079    TMSZ03
3306      76041    TMSZ03
3312      75129    TMSZ03
3313      76119    TMSZ03
3315      76051    TMSZ03
3316      76111    TMSZ03
3589      75281    TMSZ03
3762      75179    TMSZ03
3763      75171    TMSZ03
4304      75251    TMSZ03
4417      75271    TMSZ03
4605      75149    TMSZ03
4845      75099    TMSZ03
4914      75249    TMSZ03
4981      76061    TMSZ03
5096      76281    TMSZ03
5097      76289    TMSZ03
5125      75059    TMSZ03
5126      76129    TMSZ03
5127      76121    TMSZ03
5128      75051    TMSZ03
681       40301    BKSZ03
1054      43769    BKSZ03
2129      43789    BKSZ03
2214      43489    BKSZ03
2836      40309    BKSZ03
2876      43469    BKSZ03
2878      43479    BKSZ03
2888      40351    BKSZ03
2889      40359    BKSZ03
2890      40311    BKSZ03
2898      40341    BKSZ03
2899      40349    BKSZ03
2900      40321    BKSZ03
2901      40329    BKSZ03
2904      40339    BKSZ03
2962      43779    BKSZ03
3094      40361    BKSZ03
3203      40369    BKSZ03
3412      43759    BKSZ03
3672      43539    BKSZ03
4076      40379    BKSZ03
4077      40371    BKSZ03
4130      43349    BKSZ03
4467      43409    BKSZ03
5060      40331    BKSZ03
272       63081    HGSZ09
360       63091    HGSZ09
378       64229    HGSZ09
2298      64219    HGSZ09
2410      62231    HGSZ09
2496      63101    HGSZ09
2624      64209    HGSZ09
3750      62259    HGSZ09
4042      71051    HGSZ09
4271      71041    HGSZ09
4306      71061    HGSZ09
4316      62241    HGSZ09
4517      71191    HGSZ09
4640      63071    HGSZ09
4915      71031    HGSZ09
5146      71181    HGSZ09
3063      96439    CBSZ01
245       75291    PLSZ02
2515      75371    PLSZ02
2988      75411    PLSZ02
2990      75401    PLSZ02
3309      74059    PLSZ02
3310      74039    PLSZ02
17        43659    BKSZ02
124       43831    BKSZ02
432       43681    BKSZ02
460       43679    BKSZ02
684       43571    BKSZ02
702       43601    BKSZ02
714       43581    BKSZ02
1333      43481    BKSZ02
1415      43649    BKSZ02
1583      43521    BKSZ02
1717      43841    BKSZ02
2221      43839    BKSZ02
2338      43499    BKSZ02
2489      43491    BKSZ02
2875      43471    BKSZ02
3520      43641    BKSZ02
3875      43669    BKSZ02
4009      44179    BKSZ02
1061      63339    HGSZ06
1499      63319    HGSZ06
1640      63179    HGSZ06
1642      63041    HGSZ06
1762      63219    HGSZ06
2132      63169    HGSZ06
2710      63189    HGSZ06
2858      63021    HGSZ06
2859      63011    HGSZ06
4161      63209    HGSZ06
4162      63159    HGSZ06
4368      63329    HGSZ06
4613      63031    HGSZ06
4674      63199    HGSZ06
4961      63349    HGSZ06
4979      63051    HGSZ06
1057      54609    AMSZ03
1602      54299    AMSZ03
1616      54339    AMSZ03
2184      54319    AMSZ03
3286      54371    AMSZ03
3503      54379    AMSZ03
3519      54269    AMSZ03
3920      54101    AMSZ03
3921      54279    AMSZ03
4261      54369    AMSZ03
4343      54381    AMSZ03
4365      54329    AMSZ03
4556      54389    AMSZ03
4700      54289    AMSZ03
4857      54601    AMSZ03
6         66191    SGSZ04
247       66211    SGSZ04
281       66149    SGSZ04
296       66251    SGSZ04
520       66161    SGSZ04
629       66241    SGSZ04
826       66051    SGSZ04
1182      66339    SGSZ04
1209      66041    SGSZ04
1449      66309    SGSZ04
1635      66121    SGSZ04
1706      66109    SGSZ04
1725      66221    SGSZ04
1740      66031    SGSZ04
1790      63201    SGSZ04
1870      63181    SGSZ04
1927      66329    SGSZ04
2164      66131    SGSZ04
2224      66201    SGSZ04
2586      66091    SGSZ04
2602      66151    SGSZ04
2606      66129    SGSZ04
2646      66119    SGSZ04
2712      66271    SGSZ04
2713      66321    SGSZ04
3050      63211    SGSZ04
3184      66231    SGSZ04
3389      66139    SGSZ04
3595      66301    SGSZ04
3701      66319    SGSZ04
3768      66111    SGSZ04
3988      66291    SGSZ04
4107      66311    SGSZ04
4126      63361    SGSZ04
4252      66171    SGSZ04
4307      63191    SGSZ04
4455      66181    SGSZ04
4647      66261    SGSZ04
4659      54309    SGSZ04
4730      66141    SGSZ04
4763      66349    SGSZ04
392       64521    HGSZ01
550       64529    HGSZ01
576       64011    HGSZ01
796       64041    HGSZ01
897       64009    HGSZ01
1237      63061    HGSZ01
1450      64549    HGSZ01
1872      63351    HGSZ01
2514      63341    HGSZ01
3191      64391    HGSZ01
3201      64559    HGSZ01
4548      64551    HGSZ01
4644      64541    HGSZ01
4770      64381    HGSZ01
232       98039    PRSZ07
721       97201    PRSZ07
784       97111    PRSZ07
875       97121    PRSZ07
891       98059    PRSZ07
1336      98049    PRSZ07
1735      97061    PRSZ07
2039      97071    PRSZ07
2371      97081    PRSZ07
4942      98239    PRSZ07
4980      97091    PRSZ07
207       44369    BPSZ06
1006      44359    BPSZ06
1352      43869    BPSZ06
1496      43129    BPSZ06
1525      43139    BPSZ06
1540      44379    BPSZ06
1779      43859    BPSZ06
1868      44389    BPSZ06
2044      44361    BPSZ06
2051      43879    BPSZ06
3016      43961    BPSZ06
3656      43089    BPSZ06
3658      43099    BPSZ06
4083      43891    BPSZ06
4761      43889    BPSZ06
5145      44351    BPSZ06
28        78221    PRSZ05
43        98099    PRSZ05
133       78231    PRSZ05
155       78121    PRSZ05
206       78071    PRSZ05
324       78069    PRSZ05
783       78161    PRSZ05
970       78219    PRSZ05
1051      78059    PRSZ05
1101      78131    PRSZ05
1285      78179    PRSZ05
1350      78229    PRSZ05
1354      78079    PRSZ05
1442      78209    PRSZ05
1472      78189    PRSZ05
1475      78199    PRSZ05
1604      78191    PRSZ05
1623      78089    PRSZ05
2289      98091    PRSZ05
2481      78101    PRSZ05
2486      78241    PRSZ05
2531      78181    PRSZ05
2568      77059    PRSZ05
2857      98111    PRSZ05
2860      98101    PRSZ05
3218      98119    PRSZ05
3219      78141    PRSZ05
3287      78061    PRSZ05
3586      78051    PRSZ05
3617      78211    PRSZ05
3673      98011    PRSZ05
4138      78171    PRSZ05
4191      78169    PRSZ05
4273      78159    PRSZ05
4618      77051    PRSZ05
4619      78201    PRSZ05
4622      78151    PRSZ05
4802      78111    PRSZ05
4976      98021    PRSZ05
5025      78081    PRSZ05
276       75501    TMSZ01
286       75509    TMSZ01
553       75319    TMSZ01
1474      75299    TMSZ01
2154      75359    TMSZ01
2725      75279    TMSZ01
2761      75289    TMSZ01
2992      75469    TMSZ01
2993      75461    TMSZ01
3018      75369    TMSZ01
3088      75481    TMSZ01
3089      75511    TMSZ01
3090      75519    TMSZ01
3560      75541    TMSZ01
3571      75569    TMSZ01
3576      75571    TMSZ01
3577      75579    TMSZ01
3579      75559    TMSZ01
3664      75551    TMSZ01
3714      75499    TMSZ01
3730      75491    TMSZ01
3732      75488    TMSZ01
4050      75479    TMSZ01
4055      75471    TMSZ01
4620      75549    TMSZ01
4631      75561    TMSZ01
8         54411    AMSZ02
321       54571    AMSZ02
556       54271    AMSZ02
727       54589    AMSZ02
808       54479    AMSZ02
841       54291    AMSZ02
942       54419    AMSZ02
1157      54281    AMSZ02
1201      54409    AMSZ02
1308      54429    AMSZ02
1328      54441    AMSZ02
1427      54489    AMSZ02
1783      54449    AMSZ02
3196      54401    AMSZ02
3476      54261    AMSZ02
3574      54581    AMSZ02
4461      54579    AMSZ02
4463      54349    AMSZ02
4632      54439    AMSZ02
4771      54399    AMSZ02
5072      54359    AMSZ02
98        54059    AMSZ01
1634      54039    AMSZ01
2262      54391    AMSZ01
3069      54341    AMSZ01
3190      54241    AMSZ01
4397      54049    AMSZ01
4404      54251    AMSZ01
4426      54009    AMSZ01
62        54201    AMSZ06
160       54031    AMSZ06
1403      56241    AMSZ06
1844      55111    AMSZ06
2145      54209    AMSZ06
2185      56251    AMSZ06
2208      54459    AMSZ06
2534      54231    AMSZ06
2617      54041    AMSZ06
3074      54469    AMSZ06
3144      54199    AMSZ06
3666      54051    AMSZ06
3680      54221    AMSZ06
4998      54189    AMSZ06
4999      54191    AMSZ06
5046      54161    AMSZ06
750       54641    SGSZ02
939       54529    SGSZ02
1104      54631    SGSZ02
1537      54599    SGSZ02
1896      54509    SGSZ02
2102      66341    SGSZ02
2161      54301    SGSZ02
3012      54511    SGSZ02
3013      54519    SGSZ02
3422      66459    SGSZ02
3441      66519    SGSZ02
3706      54499    SGSZ02
3919      54521    SGSZ02
4291      54591    SGSZ02
4480      54659    SGSZ02
68        28161    THSZ02
757       28151    THSZ02
3738      28169    THSZ02
4406      28159    THSZ02
252       66511    SGSZ03
585       66101    SGSZ03
766       64111    SGSZ03
1189      66429    SGSZ03
1284      66431    SGSZ03
1439      66439    SGSZ03
1789      66531    SGSZ03
2002      66539    SGSZ03
3179      66509    SGSZ03
3186      66599    SGSZ03
3526      66479    SGSZ03
3702      66421    SGSZ03
3832      66529    SGSZ03
4903      66521    SGSZ03
5002      64101    SGSZ03
5123      66331    SGSZ03
631       43431    BKSZ04
693       43561    BKSZ04
700       43609    BKSZ04
705       43809    BKSZ04
708       43579    BKSZ04
1575      43569    BKSZ04
2877      43461    BKSZ04
3105      43411    BKSZ04
3109      43421    BKSZ04
3194      43541    BKSZ04
3208      43549    BKSZ04
3782      43801    BKSZ04
5109      43441    BKSZ04
123       27471    JWSZ01
787       27109    JWSZ01
812       27459    JWSZ01
890       27479    JWSZ01
1046      21381    JWSZ01
1852      27099    JWSZ01
1950      27451    JWSZ01
3468      27461    JWSZ01
3469      27469    JWSZ01
2212      43059    BPSZ07
3541      43019    BPSZ07
3657      43069    BPSZ07
3964      42119    BPSZ07
4082      43899    BPSZ07
4084      43969    BPSZ07
4243      42109    BPSZ07
4571      43049    BPSZ07
4572      43029    BPSZ07
53        76319    TMSZ02
229       76449    TMSZ02
265       76179    TMSZ02
373       76191    TMSZ02
417       76151    TMSZ02
591       76361    TMSZ02
695       76461    TMSZ02
745       76201    TMSZ02
772       76081    TMSZ02
867       76399    TMSZ02
926       76431    TMSZ02
929       76451    TMSZ02
1198      75019    TMSZ02
1248      76389    TMSZ02
1283      76471    TMSZ02
1320      75009    TMSZ02
1440      76291    TMSZ02
1574      76401    TMSZ02
1636      76071    TMSZ02
1708      76099    TMSZ02
1728      75008    TMSZ02
1811      76419    TMSZ02
1826      76089    TMSZ02
1848      76351    TMSZ02
1851      76079    TMSZ02
1938      76131    TMSZ02
1965      76149    TMSZ02
1971      76251    TMSZ02
2016      76349    TMSZ02
2056      76359    TMSZ02
2087      76261    TMSZ02
2108      76161    TMSZ02
2165      76459    TMSZ02
2301      76429    TMSZ02
2332      76091    TMSZ02
2404      76439    TMSZ02
2416      76139    TMSZ02
2543      76271    TMSZ02
2553      76159    TMSZ02
2581      76371    TMSZ02
2662      76101    TMSZ02
2698      76441    TMSZ02
2721      76519    TMSZ02
2759      76541    TMSZ02
2908      76279    TMSZ02
3043      76031    TMSZ02
3044      76039    TMSZ02
3046      76511    TMSZ02
3047      76529    TMSZ02
3102      76311    TMSZ02
3110      76411    TMSZ02
3111      76181    TMSZ02
3112      76189    TMSZ02
3113      76341    TMSZ02
3114      76259    TMSZ02
3223      76521    TMSZ02
3314      76059    TMSZ02
3341      76339    TMSZ02
3392      76241    TMSZ02
3398      76249    TMSZ02
3415      76141    TMSZ02
3416      76199    TMSZ02
3532      75121    TMSZ02
3648      76069    TMSZ02
3700      76409    TMSZ02
3769      76421    TMSZ02
3845      76469    TMSZ02
4041      75269    TMSZ02
4046      76209    TMSZ02
4182      76269    TMSZ02
4411      76301    TMSZ02
4431      76169    TMSZ02
4497      76559    TMSZ02
4555      76369    TMSZ02
4585      76219    TMSZ02
4621      76391    TMSZ02
4660      76221    TMSZ02
4661      76229    TMSZ02
4662      76211    TMSZ02
4791      76551    TMSZ02
4830      76329    TMSZ02
4880      76231    TMSZ02
4881      76239    TMSZ02
4898      76109    TMSZ02
5023      76171    TMSZ02
320       63269    HGSZ07
625       63139    HGSZ07
776       62059    HGSZ07
971       63229    HGSZ07
1083      63241    HGSZ07
1181      63039    HGSZ07
1301      63261    HGSZ07
1361      63019    HGSZ07
1381      63299    HGSZ07
1503      63099    HGSZ07
1515      63131    HGSZ07
1590      62229    HGSZ07
2217      62219    HGSZ07
2429      63089    HGSZ07
2853      63221    HGSZ07
2856      63029    HGSZ07
3056      63271    HGSZ07
3231      63309    HGSZ07
3473      63231    HGSZ07
3474      63239    HGSZ07
4293      63079    HGSZ07
4452      63281    HGSZ07
4639      63279    HGSZ07
4650      63289    HGSZ07
4752      63049    HGSZ07
4978      63059    HGSZ07
271       97051    PRSZ08
316       97119    PRSZ08
383       97101    PRSZ08
488       98311    PRSZ08
617       98081    PRSZ08
997       98029    PRSZ08
1103      97129    PRSZ08
1564      98291    PRSZ08
1647      98299    PRSZ08
2390      98319    PRSZ08
2635      97011    PRSZ08
3770      97041    PRSZ08
4334      98089    PRSZ08
4500      97031    PRSZ08
4503      98301    PRSZ08
4588      98309    PRSZ08
4723      97109    PRSZ08
4977      98019    PRSZ08
40        43301    BKSZ05
219       43309    BKSZ05
600       43151    BKSZ05
624       43289    BKSZ05
758       43268    BKSZ05
853       43271    BKSZ05
1027      43231    BKSZ05
1166      43819    BKSZ05
1224      43239    BKSZ05
1481      43249    BKSZ05
1865      43267    BKSZ05
1921      43041    BKSZ05
2042      43259    BKSZ05
2183      43251    BKSZ05
2199      43241    BKSZ05
2322      43229    BKSZ05
2360      43291    BKSZ05
2675      43811    BKSZ05
2777      42991    BKSZ05
2886      43261    BKSZ05
2966      43061    BKSZ05
3176      43051    BKSZ05
3653      43071    BKSZ05
3814      43639    BKSZ05
4569      43829    BKSZ05
4570      43821    BKSZ05
4573      43021    BKSZ05
4628      43209    BKSZ05
4910      43279    BKSZ05
4959      43159    BKSZ05
1479      28661    CLSZ01
1513      28699    CLSZ01
1580      28671    CLSZ01
1626      28039    CLSZ01
1688      28019    CLSZ01
2308      12201    CLSZ01
2649      28689    CLSZ01
2979      28029    CLSZ01
3486      28709    CLSZ01
3547      28181    CLSZ01
3939      28109    CLSZ01
4154      28679    CLSZ01
4194      28189    CLSZ01
4532      28681    CLSZ01
4946      28701    CLSZ01
4950      28669    CLSZ01
4952      28691    CLSZ01
5047      28101    CLSZ01
255       41159    NVSZ05
774       40259    NVSZ05
849       51101    NVSZ05
1062      51051    NVSZ05
1690      51041    NVSZ05
2396      41149    NVSZ05
3818      51091    NVSZ05
3872      41169    NVSZ05
3984      40269    NVSZ05
4430      51031    NVSZ05
4446      51021    NVSZ05
4546      51119    NVSZ05
687       41131    BTSZ05
960       41069    BTSZ05
1407      41049    BTSZ05
2256      41141    BTSZ05
2344      41089    BTSZ05
2591      41121    BTSZ05
3167      41079    BTSZ05
100       70291    TPSZ12
1931      70049    TPSZ12
2066      70121    TPSZ12
2872      62061    TPSZ12
3067      70281    TPSZ12
3101      70141    TPSZ12
4474      70131    TPSZ12
4768      70301    TPSZ12
4879      70059    TPSZ12
197       21211    JWSZ05
248       21531    JWSZ05
330       21521    JWSZ05
846       21201    JWSZ05
850       21259    JWSZ05
1567      21349    JWSZ05
1920      21691    JWSZ05
2075      21681    JWSZ05
2082      21339    JWSZ05
2353      21509    JWSZ05
3270      21529    JWSZ05
3289      21511    JWSZ05
3290      21519    JWSZ05
3543      21261    JWSZ05
3695      21539    JWSZ05
3909      21501    JWSZ05
3967      21269    JWSZ05
4242      21359    JWSZ05
4703      21251    JWSZ05
1979      52381    TPSZ05
3298      52539    TPSZ05
3299      52529    TPSZ05
3300      52069    TPSZ05
3301      52361    TPSZ05
3303      52059    TPSZ05
3305      52351    TPSZ05
4963      52371    TPSZ05
139       28631    JESZ03
641       28639    JESZ03
1056      28629    JESZ03
1275      28069    JESZ03
1282      28319    JESZ03
2241      28649    JESZ03
2912      28049    JESZ03
3723      28651    JESZ03
3801      28659    JESZ03
5056      28641    JESZ03
470       52271    TPSZ03
511       52029    TPSZ03
1256      52229    TPSZ03
1374      52221    TPSZ03
2561      52209    TPSZ03
3292      52369    TPSZ03
3293      52449    TPSZ03
3297      52441    TPSZ03
4410      52179    TPSZ03
4776      52039    TPSZ03
532       62071    TPSZ10
633       62091    TPSZ10
925       61049    TPSZ10
3322      61039    TPSZ10
3868      70069    TPSZ10
4332      62101    TPSZ10
4765      62081    TPSZ10
598       66089    TPSZ08
2257      66069    TPSZ08
2637      61041    TPSZ08
3320      61021    TPSZ08
3337      61031    TPSZ08
3663      66079    TPSZ08
192       21611    JWSZ04
346       21559    JWSZ04
353       28091    JWSZ04
484       21541    JWSZ04
539       21591    JWSZ04
713       21609    JWSZ04
856       21279    JWSZ04
1125      21621    JWSZ04
1151      21209    JWSZ04
1156      21029    JWSZ04
1772      21191    JWSZ04
1773      21199    JWSZ04
1815      21581    JWSZ04
2117      21601    JWSZ04
2252      21641    JWSZ04
2364      21679    JWSZ04
2613      21571    JWSZ04
3340      21271    JWSZ04
3478      21779    JWSZ04
3524      21661    JWSZ04
3565      21751    JWSZ04
3584      21589    JWSZ04
3795      21219    JWSZ04
3813      21189    JWSZ04
4094      21551    JWSZ04
4143      21629    JWSZ04
4183      21599    JWSZ04
4241      21631    JWSZ04
4275      21651    JWSZ04
4348      21671    JWSZ04
4412      21579    JWSZ04
4434      21761    JWSZ04
4441      21179    JWSZ04
4545      21619    JWSZ04
4948      21229    JWSZ04
4988      21569    JWSZ04
4989      21561    JWSZ04
4993      21771    JWSZ04
303       28351    JESZ04
611       28341    JESZ04
1632      21659    JESZ04
2155      21019    JESZ04
2426      21769    JESZ04
2502      21669    JESZ04
3630      28371    JESZ04
3885      21639    JESZ04
4002      21649    JESZ04
4256      28271    JESZ04
4593      28361    JESZ04
4641      21759    JESZ04
57        52141    TPSZ01
65        51069    TPSZ01
701       52249    TPSZ01
722       52159    TPSZ01
820       52201    TPSZ01
895       51059    TPSZ01
1216      52169    TPSZ01
1897      51139    TPSZ01
3096      52211    TPSZ01
3274      52019    TPSZ01
3380      51089    TPSZ01
3426      52219    TPSZ01
3429      52551    TPSZ01
3440      52559    TPSZ01
3471      51079    TPSZ01
4068      52151    TPSZ01
4444      52161    TPSZ01
4469      51081    TPSZ01
4878      52241    TPSZ01
5050      52171    TPSZ01
237       71071    BDSZ01
349       84701    BDSZ01
932       71291    BDSZ01
935       71299    BDSZ01
1371      84501    BDSZ01
1906      84511    BDSZ01
2008      84491    BDSZ01
2557      84499    BDSZ01
2608      72081    BDSZ01
2609      72089    BDSZ01
2944      72149    BDSZ01
2945      72141    BDSZ01
2946      72131    BDSZ01
2947      72139    BDSZ01
3033      71331    BDSZ01
3034      71339    BDSZ01
3039      72151    BDSZ01
3040      72161    BDSZ01
3041      72159    BDSZ01
3042      72169    BDSZ01
3147      72019    BDSZ01
3557      72071    BDSZ01
3600      72079    BDSZ01
3880      72059    BDSZ01
4516      72051    BDSZ01
4564      71091    BDSZ01
4574      72029    BDSZ01
4575      84709    BDSZ01
4576      72049    BDSZ01
4577      72041    BDSZ01
4578      72039    BDSZ01
4579      72031    BDSZ01
4580      72061    BDSZ01
4581      72021    BDSZ01
4582      72069    BDSZ01
4745      71081    BDSZ01
4884      84489    BDSZ01
4885      84481    BDSZ01
5131      84451    BDSZ01
200       28439    JESZ02
372       28621    JESZ02
574       28259    JESZ02
912       28441    JESZ02
1108      28311    JESZ02
1138      28279    JESZ02
1149      28081    JESZ02
1222      28331    JESZ02
1311      28339    JESZ02
1504      28269    JESZ02
1905      28071    JESZ02
2053      28329    JESZ02
2357      28289    JESZ02
3177      28321    JESZ02
3516      28079    JESZ02
4152      28299    JESZ02
5113      28089    JESZ02
111       43311    BKSZ09
146       43611    BKSZ09
183       43591    BKSZ09
385       43511    BKSZ09
638       43621    BKSZ09
671       43509    BKSZ09
822       43219    BKSZ09
1203      43211    BKSZ09
1317      43319    BKSZ09
1368      42209    BKSZ09
1369      42201    BKSZ09
1724      43619    BKSZ09
1991      43191    BKSZ09
2530      43699    BKSZ09
2855      43501    BKSZ09
3211      43629    BKSZ09
3352      43149    BKSZ09
3490      42319    BKSZ09
3899      42291    BKSZ09
4519      42311    BKSZ09
151       22259    JWSZ09
397       22509    JWSZ09
409       22449    JWSZ09
501       22501    JWSZ09
662       22459    JWSZ09
676       21371    JWSZ09
743       22491    JWSZ09
986       22411    JWSZ09
1117      22481    JWSZ09
1220      22341    JWSZ09
1438      22231    JWSZ09
1660      22529    JWSZ09
1996      22579    JWSZ09
2092      22501    JWSZ09
2122      22441    JWSZ09
2203      21361    JWSZ09
2253      22009    JWSZ09
2389      22521    JWSZ09
2507      22469    JWSZ09
2585      22361    JWSZ09
3015      22561    JWSZ09
3927      22499    JWSZ09
4502      22511    JWSZ09
4625      22599    JWSZ09
4778      22249    JWSZ09
4779      22531    JWSZ09
4780      22239    JWSZ09
4781      22241    JWSZ09
4788      22489    JWSZ09
4866      22519    JWSZ09
4867      22539    JWSZ09
5003      22541    JWSZ09
5005      22351    JWSZ09
5034      22551    JWSZ09
5049      22251    JWSZ09
5140      22591    JWSZ09
290       84479    BDSZ02
382       84619    BDSZ02
589       84621    BDSZ02
674       84471    BDSZ02
888       75349    BDSZ02
1084      75341    BDSZ02
1265      84469    BDSZ02
1507      84459    BDSZ02
1819      84461    BDSZ02
2264      84639    BDSZ02
2379      84609    BDSZ02
2539      84629    BDSZ02
2873      84201    BDSZ02
3066      84209    BDSZ02
3922      84611    BDSZ02
4324      84601    BDSZ02
4511      84539    BDSZ02
4533      84631    BDSZ02
186       42229    BTSZ01
256       42191    BTSZ01
266       42299    BTSZ01
762       12091    BTSZ01
824       42241    BTSZ01
1114      12081    BTSZ01
1242      12101    BTSZ01
1310      43201    BTSZ01
1763      42199    BTSZ01
1849      43011    BTSZ01
1943      42161    BTSZ01
2114      42169    BTSZ01
2306      42249    BTSZ01
2432      42171    BTSZ01
2722      42079    BTSZ01
2844      42111    BTSZ01
3437      42259    BTSZ01
3480      42141    BTSZ01
3496      42239    BTSZ01
3498      42151    BTSZ01
3545      42181    BTSZ01
3965      42159    BTSZ01
4079      42099    BTSZ01
4117      42231    BTSZ01
4193      42211    BTSZ01
4199      42219    BTSZ01
4207      43631    BTSZ01
4212      42071    BTSZ01
4237      42221    BTSZ01
4509      42309    BTSZ01
4520      42091    BTSZ01
4524      42179    BTSZ01
4926      42301    BTSZ01
5129      42189    BTSZ01
12        42089    BTSZ02
60        42039    BTSZ02
1543      42029    BTSZ02
3487      42049    BTSZ02
4664      42019    BTSZ02
4918      42059    BTSZ02
75        96391    TMSZ05
375       96271    TMSZ05
775       96321    TMSZ05
1383      96029    TMSZ05
1807      96239    TMSZ05
2291      96231    TMSZ05
2536      96351    TMSZ05
2600      96221    TMSZ05
2626      96241    TMSZ05
2932      96411    TMSZ05
2951      95909    TMSZ05
2953      96449    TMSZ05
2954      96441    TMSZ05
2956      96049    TMSZ05
2983      96059    TMSZ05
2987      96389    TMSZ05
2994      96419    TMSZ05
3037      96401    TMSZ05
3038      97009    TMSZ05
3264      96319    TMSZ05
3265      96319    TMSZ05
3590      96069    TMSZ05
3756      96381    TMSZ05
3757      96301    TMSZ05
3758      96309    TMSZ05
4214      96331    TMSZ05
4217      96311    TMSZ05
4218      96361    TMSZ05
4299      96371    TMSZ05
4475      96249    TMSZ05
4493      96229    TMSZ05
4591      96329    TMSZ05
4592      96341    TMSZ05
4646      96019    TMSZ05
4863      96039    TMSZ05
4         96081    TMSZ04
10        96139    TMSZ04
125       96061    TMSZ04
359       84431    TMSZ04
604       84271    TMSZ04
615       96131    TMSZ04
643       96159    TMSZ04
680       96169    TMSZ04
1085      96171    TMSZ04
1105      84591    TMSZ04
1164      96121    TMSZ04
1501      96109    TMSZ04
1556      96071    TMSZ04
1821      96011    TMSZ04
1953      96141    TMSZ04
1970      85079    TMSZ04
2052      96129    TMSZ04
2106      84599    TMSZ04
2171      96111    TMSZ04
2181      96191    TMSZ04
2195      84299    TMSZ04
2343      96089    TMSZ04
2355      84279    TMSZ04
2382      96189    TMSZ04
2427      96151    TMSZ04
2555      96181    TMSZ04
2569      96199    TMSZ04
2641      96101    TMSZ04
2667      96161    TMSZ04
2952      95901    TMSZ04
2955      96041    TMSZ04
2982      96051    TMSZ04
3035      96201    TMSZ04
3036      96209    TMSZ04
3244      96079    TMSZ04
3251      96119    TMSZ04
3267      96269    TMSZ04
3282      96149    TMSZ04
3381      96299    TMSZ04
3838      96261    TMSZ04
3990      96021    TMSZ04
4375      96291    TMSZ04
4489      84439    TMSZ04
4637      85071    TMSZ04
4803      96179    TMSZ04
4865      96091    TMSZ04
4947      96031    TMSZ04
4953      96099    TMSZ04
5110      96289    TMSZ04
5120      96251    TMSZ04
5121      96259    TMSZ04
5122      96281    TMSZ04
72        21421    JWSZ02
239       21431    JWSZ02
263       21369    JWSZ02
323       21379    JWSZ02
341       21399    JWSZ02
500       21391    JWSZ02
706       21451    JWSZ02
936       21439    JWSZ02
1034      21449    JWSZ02
1286      21411    JWSZ02
1482      21409    JWSZ02
1639      21689    JWSZ02
1685      21419    JWSZ02
1857      21459    JWSZ02
1861      21441    JWSZ02
1899      21249    JWSZ02
3229      21241    JWSZ02
3456      21161    JWSZ02
4056      21389    JWSZ02
4384      21429    JWSZ02
4861      21231    JWSZ02
4951      21699    JWSZ02
4955      21719    JWSZ02
319       43439    BKSZ08
901       43449    BKSZ08
1390      43169    BKSZ08
2483      43221    BKSZ08
2625      43179    BKSZ08
3447      43199    BKSZ08
4190      43429    BKSZ08
4367      43161    BKSZ08
4695      43189    BKSZ08
292       43531    BKSZ06
335       43379    BKSZ06
601       43341    BKSZ06
1386      43691    BKSZ06
2240      43331    BKSZ06
2778      43453    BKSZ06
2779      43452    BKSZ06
2902      43339    BKSZ06
3692      43351    BKSZ06
3709      43329    BKSZ06
4080      43359    BKSZ06
4081      43369    BKSZ06
4787      43361    BKSZ06
396       43739    BKSZ07
1268      43519    BKSZ07
1351      43389    BKSZ07
1465      43171    BKSZ07
1609      43709    BKSZ07
1910      43401    BKSZ07
3103      43749    BKSZ07
3104      43741    BKSZ07
3222      43381    BKSZ07
3227      43181    BKSZ07
3350      43731    BKSZ07
3351      43141    BKSZ07
3410      43701    BKSZ07
3411      43709    BKSZ07
3983      43009    BKSZ07
4088      43599    BKSZ07
4093      43371    BKSZ07
4120      43391    BKSZ07
4137      43399    BKSZ07
4774      43419    BKSZ07
5161      43321    BKSZ07
18        62099    SGSZ07
55        62109    SGSZ07
1278      62031    SGSZ07
1516      62041    SGSZ07
1534      62179    SGSZ07
1738      62119    SGSZ07
2120      62139    SGSZ07
2271      62161    SGSZ07
2660      62021    SGSZ07
2845      62011    SGSZ07
2864      62069    SGSZ07
3242      62149    SGSZ07
3933      62159    SGSZ07
4301      62051    SGSZ07
4711      62171    SGSZ07
4756      62151    SGSZ07
4760      62189    SGSZ07
4762      62169    SGSZ07
4766      62089    SGSZ07
4829      62079    SGSZ07
4874      62129    SGSZ07
140       63109    HGSZ08
269       71021    HGSZ08
933       62239    HGSZ08
1169      62039    HGSZ08
1612      62049    HGSZ08
1876      70299    HGSZ08
1917      62221    HGSZ08
1976      70289    HGSZ08
2517      62249    HGSZ08
2610      63291    HGSZ08
2846      62019    HGSZ08
2847      62029    HGSZ08
3009      71171    HGSZ08
3285      63301    HGSZ08
3674      71059    HGSZ08
4136      71011    HGSZ08
4305      71069    HGSZ08
4767      70309    HGSZ08
221       25221    TSSZ01
1605      25231    TSSZ01
2238      25269    TSSZ01
3640      24509    TSSZ01
404       28281    JESZ01
412       28349    JESZ01
457       28461    JESZ01
579       28459    JESZ01
1129      28451    JESZ01
1143      28291    JESZ01
1670      28481    JESZ01
3597      28469    JESZ01
3802      28471    JESZ01
4292      28359    JESZ01
5000      28499    JESZ01
5076      28491    JESZ01
86        27301    JWSZ08
94        27149    JWSZ08
107       27141    JWSZ08
141       27409    JWSZ08
234       27431    JWSZ08
240       27419    JWSZ08
246       27449    JWSZ08
270       22359    JWSZ08
274       27391    JWSZ08
280       22369    JWSZ08
339       27379    JWSZ08
522       22451    JWSZ08
677       27091    JWSZ08
805       27369    JWSZ08
900       27371    JWSZ08
1326      27439    JWSZ08
1327      27441    JWSZ08
1432      22419    JWSZ08
1718      27381    JWSZ08
1845      27131    JWSZ08
1914      27411    JWSZ08
2232      27389    JWSZ08
2266      27361    JWSZ08
2565      27271    JWSZ08
2665      27519    JWSZ08
2790      27401    JWSZ08
3509      27101    JWSZ08
3511      27331    JWSZ08
3631      27329    JWSZ08
3728      27139    JWSZ08
3729      27429    JWSZ08
3834      27341    JWSZ08
4011      27309    JWSZ08
4012      27321    JWSZ08
4023      27511    JWSZ08
4171      27421    JWSZ08
4402      27531    JWSZ08
4419      27399    JWSZ08
4450      22461    JWSZ08
4531      27351    JWSZ08
4599      27539    JWSZ08
4600      27501    JWSZ08
4601      27529    JWSZ08
4602      27509    JWSZ08
4609      27521    JWSZ08
4722      27349    JWSZ08
4749      27359    JWSZ08
4906      27279    JWSZ08
4965      22471    JWSZ08
4974      22349    JWSZ08
5045      27159    JWSZ08
469       66071    SGSZ05
1021      62111    SGSZ05
1041      66011    SGSZ05
1069      66409    SGSZ05
1073      66061    SGSZ05
1124      66399    SGSZ05
2103      66099    SGSZ05
2124      66081    SGSZ05
4054      66029    SGSZ05
4345      66019    SGSZ05
5158      66021    SGSZ05
9         28531    JWSZ03
81        28521    JWSZ03
161       28501    JWSZ03
198       28571    JWSZ03
736       28581    JWSZ03
917       28511    JWSZ03
1016      28409    JWSZ03
1186      28561    JWSZ03
1193      21711    JWSZ03
1292      28601    JWSZ03
1305      28391    JWSZ03
1611      28389    JWSZ03
1641      28369    JWSZ03
1677      28401    JWSZ03
1683      28381    JWSZ03
1749      28399    JWSZ03
2012      28529    JWSZ03
2073      28519    JWSZ03
2377      28541    JWSZ03
2398      21239    JWSZ03
2753      28379    JWSZ03
3387      28421    JWSZ03
3457      21169    JWSZ03
3598      28551    JWSZ03
4260      28611    JWSZ03
4737      28591    JWSZ03
4764      28411    JWSZ03
4805      28099    JWSZ03
4844      28509    JWSZ03
5063      28539    JWSZ03
489       68111    SLSZ04
1191      68201    SLSZ04
1321      68091    SLSZ04
1954      68119    SLSZ04
2656      68099    SLSZ04
3752      68091    SLSZ04
4377      68061    SLSZ04
5071      68069    SLSZ04
1052      49049    SKSZ04
1126      49019    SKSZ04
1127      49021    SKSZ04
1150      49041    SKSZ04
1199      49031    SKSZ04
1367      49011    SKSZ04
1421      49029    SKSZ04
1562      49039    SKSZ04
2168      49139    SKSZ04
4909      49131    SKSZ04
48        68131    SLSZ01
458       68139    SLSZ01
829       68239    SLSZ01
1805      68101    SLSZ01
1929      68159    SLSZ01
3146      68141    SLSZ01
3168      68149    SLSZ01
3361      68209    SLSZ01
3753      68099    SLSZ01
4213      68089    SLSZ01
4216      68081    SLSZ01
4296      68121    SLSZ01
4300      68109    SLSZ01
4396      68151    SLSZ01
4596      68129    SLSZ01
4670      68161    SLSZ01
4671      68169    SLSZ01
474       59321    YSSZ08
475       59561    YSSZ08
481       59329    YSSZ08
657       57069    YSSZ08
865       59051    YSSZ08
904       59559    YSSZ08
1541      57079    YSSZ08
1866      57059    YSSZ08
1882      59339    YSSZ08
2477      59031    YSSZ08
3091      59549    YSSZ08
4720      59041    YSSZ08
4769      59569    YSSZ08
164       48011    MDSZ01
1544      48031    MDSZ01
1834      48021    MDSZ01
3546      48061    MDSZ01
4418      48041    MDSZ01
4893      48051    MDSZ01
174       59441    YSSZ04
411       59299    YSSZ04
467       59379    YSSZ04
477       59439    YSSZ04
723       59349    YSSZ04
892       59049    YSSZ04
1002      59459    YSSZ04
1145      59289    YSSZ04
1154      59291    YSSZ04
1519      59059    YSSZ04
1643      59431    YSSZ04
1925      59369    YSSZ04
2095      59371    YSSZ04
2148      59361    YSSZ04
2444      59421    YSSZ04
2446      59429    YSSZ04
2512      59481    YSSZ04
2695      59721    YSSZ04
3170      59631    YSSZ04
3400      59711    YSSZ04
4021      59709    YSSZ04
4351      59039    YSSZ04
4362      59281    YSSZ04
4534      59571    YSSZ04
4751      59501    YSSZ04
4943      59499    YSSZ04
172       59789    YSSZ05
594       59449    YSSZ05
2033      59019    YSSZ05
2693      59479    YSSZ05
2694      59589    YSSZ05
2696      59729    YSSZ05
2697      59741    YSSZ05
2765      59759    YSSZ05
2766      59751    YSSZ05
2767      59749    YSSZ05
2774      59731    YSSZ05
2775      59739    YSSZ05
2776      59761    YSSZ05
2818      59779    YSSZ05
2907      59509    YSSZ05
2978      59719    YSSZ05
3629      55271    YSSZ05
3779      55289    YSSZ05
4297      68171    YSSZ05
4298      68179    YSSZ05
4342      59029    YSSZ05
1070      65129    PGSZ01
1233      65629    PGSZ01
1236      65621    PGSZ01
1238      65631    PGSZ01
1240      65639    PGSZ01
1366      65119    PGSZ01
2462      65111    PGSZ01
3592      65641    PGSZ01
3602      65681    PGSZ01
4339      65139    PGSZ01
4964      65689    PGSZ01
4966      65661    PGSZ01
4968      65651    PGSZ01
362       57081    MDSZ03
1035      57071    MDSZ03
1059      59351    YSSZ01
1235      59341    YSSZ01
2394      59069    YSSZ01
3185      59073    YSSZ01
3332      59161    YSSZ01
3727      59701    YSSZ01
3731      59691    YSSZ01
4015      59669    YSSZ01
4044      59072    YSSZ01
4317      59661    YSSZ01
4321      59699    YSSZ01
4815      59619    YSSZ01
4816      59611    YSSZ01
154       77131    PRSZ03
315       77369    PRSZ03
377       77199    PRSZ03
494       77179    PRSZ03
1257      77008    PRSZ03
1387      77009    PRSZ03
1483      77341    PRSZ03
1594      77361    PRSZ03
1694      77321    PRSZ03
1806      77041    PRSZ03
2346      77139    PRSZ03
2381      77021    PRSZ03
2537      77381    PRSZ03
2540      77389    PRSZ03
3100      77371    PRSZ03
3234      77379    PRSZ03
3250      77141    PRSZ03
3255      77329    PRSZ03
3261      77329    PRSZ03
3263      77029    PRSZ03
3708      77019    PRSZ03
3892      77359    PRSZ03
4123      77351    PRSZ03
4269      77191    PRSZ03
4567      77011    PRSZ03
4773      77171    PRSZ03
4868      77349    PRSZ03
4869      77049    PRSZ03
4870      77039    PRSZ03
5080      77031    PRSZ03
658       43721    BKSZ01
710       43589    BKSZ01
1183      44011    BKSZ01
1514      44159    BKSZ01
1873      44139    BKSZ01
2263      43719    BKSZ01
2321      44149    BKSZ01
2598      43529    BKSZ01
3635      44169    BKSZ01
3654      43111    BKSZ01
3659      43091    BKSZ01
3660      43081    BKSZ01
4327      44021    BKSZ01
1491      75381    PLSZ01
1928      75361    PLSZ01
2146      75351    PLSZ01
3058      74041    PLSZ01
3059      74049    PLSZ01
3078      74021    PLSZ01
3079      74011    PLSZ01
3082      73031    PLSZ01
3308      74051    PLSZ01
3311      74031    PLSZ01
3869      75391    PLSZ01
4633      75311    PLSZ01
104       64029    HGSZ03
166       62251    HGSZ03
241       64371    HGSZ03
759       64429    HGSZ03
1402      64421    HGSZ03
1506      64051    HGSZ03
1606      64079    HGSZ03
1730      64021    HGSZ03
2004      64071    HGSZ03
2142      64031    HGSZ03
2237      62251    HGSZ03
2419      64039    HGSZ03
3245      67719    HGSZ03
4013      62271    HGSZ03
4374      64401    HGSZ03
4429      67739    HGSZ03
4498      67729    HGSZ03
5006      64061    HGSZ03
5022      64571    HGSZ03
222       64221    HGSZ10
2871      64211    HGSZ10
4174      64131    HGSZ10
438       64059    HGSZ02
547       64069    HGSZ02
733       64239    HGSZ02
848       64409    HGSZ02
1185      64231    HGSZ02
1289      64049    HGSZ02
1550      64241    HGSZ02
1972      63249    HGSZ02
2019      64319    HGSZ02
2972      64301    HGSZ02
2973      64309    HGSZ02
3668      63069    HGSZ02
3774      64201    HGSZ02
4045      64321    HGSZ02
4062      64019    HGSZ02
4587      62261    HGSZ02
4709      64329    HGSZ02
5016      64249    HGSZ02
5052      64311    HGSZ02
184       56039    AMSZ07
1572      56019    AMSZ07
1816      56259    AMSZ07
1957      55121    AMSZ07
2476      56209    AMSZ07
2715      56029    AMSZ07
2716      56011    AMSZ07
3822      56031    AMSZ07
3850      56199    AMSZ07
4710      56249    AMSZ07
5160      56021    AMSZ07
262       43121    BPSZ05
365       44191    BPSZ05
381       44219    BPSZ05
618       44639    BPSZ05
660       44201    BPSZ05
685       44211    BPSZ05
828       44221    BPSZ05
1130      44029    BPSZ05
1863      44239    BPSZ05
2020      44631    BPSZ05
2077      44259    BPSZ05
2556      44859    BPSZ05
2679      44031    BPSZ05
2691      44909    BPSZ05
2849      45009    BPSZ05
3169      44249    BPSZ05
3652      43119    BPSZ05
3655      43109    BPSZ05
3745      43131    BPSZ05
3767      44199    BPSZ05
4283      44019    BPSZ05
4565      44731    BPSZ05
4566      44739    BPSZ05
4758      44209    BPSZ05
214       44091    CKSZ02
450       44129    CKSZ02
612       44081    CKSZ02
996       44151    CKSZ02
1303      44511    CKSZ02
1531      44579    CKSZ02
1827      44101    CKSZ02
2138      44459    CKSZ02
2831      30111    CKSZ02
2833      30121    CKSZ02
2903      44881    CKSZ02
2906      44599    CKSZ02
3060      45451    CKSZ02
3370      44181    CKSZ02
3372      44189    CKSZ02
3612      44569    CKSZ02
3634      44161    CKSZ02
3998      44449    CKSZ02
4310      44571    CKSZ02
4436      44521    CKSZ02
4527      44109    CKSZ02
4685      44561    CKSZ02
5114      44899    CKSZ02
5115      44891    CKSZ02
5116      44879    CKSZ02
5117      44871    CKSZ02
5118      44889    CKSZ02
29        63359    HGSZ04
134       63389    HGSZ04
250       64449    HGSZ04
277       63381    HGSZ04
350       64579    HGSZ04
650       64419    HGSZ04
719       63371    HGSZ04
771       64479    HGSZ04
1137      64361    HGSZ04
1162      64609    HGSZ04
1510      64339    HGSZ04
1536      64439    HGSZ04
1786      64109    HGSZ04
1878      63331    HGSZ04
1907      63379    HGSZ04
1924      64411    HGSZ04
2068      63321    HGSZ04
2169      64379    HGSZ04
2283      64331    HGSZ04
2595      63311    HGSZ04
3053      64621    HGSZ04
3205      64399    HGSZ04
3256      67629    HGSZ04
3627      64369    HGSZ04
3707      63399    HGSZ04
4108      64359    HGSZ04
4125      64351    HGSZ04
4180      64349    HGSZ04
4249      64341    HGSZ04
4353      64389    HGSZ04
4850      63391    HGSZ04
30        64141    PLSZ03
1477      64181    PLSZ03
2418      64161    PLSZ03
3081      73021    PLSZ03
3085      64191    PLSZ03
4027      64151    PLSZ03
4747      64171    PLSZ03
3         44331    BPSZ04
1281      44301    BPSZ04
1822      44321    BPSZ04
1871      44269    BPSZ04
2363      44371    BPSZ04
2640      44381    BPSZ04
3504      44261    BPSZ04
3863      44929    BPSZ04
4111      44329    BPSZ04
4557      44229    BPSZ04
4939      44311    BPSZ04
163       44499    CKSZ04
295       44501    CKSZ04
430       44589    CKSZ04
433       44581    CKSZ04
731       44089    CKSZ04
909       44689    CKSZ04
993       44509    CKSZ04
1337      44559    CKSZ04
1558      44071    CKSZ04
1946      44491    CKSZ04
2098      44079    CKSZ04
2153      44629    CKSZ04
2254      30081    CKSZ04
2835      30101    CKSZ04
2905      44591    CKSZ04
3166      44529    CKSZ04
3388      44519    CKSZ04
3873      44551    CKSZ04
4192      44469    CKSZ04
4360      45231    CKSZ04
4479      44621    CKSZ04
38        77099    PRSZ02
127       77259    PRSZ02
195       77251    PRSZ02
249       77221    PRSZ02
314       77249    PRSZ02
678       77281    PRSZ02
754       77079    PRSZ02
869       77261    PRSZ02
946       77089    PRSZ02
961       77209    PRSZ02
1095      77219    PRSZ02
1245      77111    PRSZ02
1345      77201    PRSZ02
1713      77319    PRSZ02
1814      77181    PRSZ02
1879      77161    PRSZ02
1915      77101    PRSZ02
1963      77211    PRSZ02
2007      77331    PRSZ02
2057      77301    PRSZ02
2218      77309    PRSZ02
2270      77311    PRSZ02
2680      77169    PRSZ02
2681      77231    PRSZ02
2975      77291    PRSZ02
3068      77241    PRSZ02
3171      78049    PRSZ02
3928      77081    PRSZ02
4022      77239    PRSZ02
4052      77071    PRSZ02
4147      77061    PRSZ02
4395      77189    PRSZ02
4398      77069    PRSZ02
4409      77091    PRSZ02
4606      77289    PRSZ02
4742      77109    PRSZ02
4907      77271    PRSZ02
180       55159    AMSZ09
858       55139    AMSZ09
1334      55181    AMSZ09
1533      55119    AMSZ09
1982      55171    AMSZ09
2069      55141    AMSZ09
2454      54451    AMSZ09
3075      54461    AMSZ09
3087      55201    AMSZ09
3200      55199    AMSZ09
3207      55169    AMSZ09
3450      55019    AMSZ09
4168      55149    AMSZ09
4470      55029    AMSZ09
4551      55151    AMSZ09
4617      55129    AMSZ09
5074      55131    AMSZ09
131       64129    HGSZ05
152       66581    HGSZ05
258       66499    HGSZ05
273       64611    HGSZ05
291       64489    HGSZ05
419       64441    HGSZ05
495       66569    HGSZ05
498       66589    HGSZ05
588       64491    HGSZ05
1017      64461    HGSZ05
1131      64119    HGSZ05
1133      64431    HGSZ05
1148      64471    HGSZ05
1270      66491    HGSZ05
1408      66489    HGSZ05
1489      66559    HGSZ05
1490      66561    HGSZ05
1747      64091    HGSZ05
1756      64469    HGSZ05
1775      66579    HGSZ05
1801      64509    HGSZ05
1831      64499    HGSZ05
1981      67061    HGSZ05
2348      64561    HGSZ05
2366      64601    HGSZ05
2385      66481    HGSZ05
2819      64099    HGSZ05
2820      64251    HGSZ05
2821      64089    HGSZ05
2822      64081    HGSZ05
2943      66551    HGSZ05
3054      64629    HGSZ05
3344      66601    HGSZ05
3345      66571    HGSZ05
3346      66609    HGSZ05
3573      64519    HGSZ05
3721      66611    HGSZ05
3725      66619    HGSZ05
3776      64481    HGSZ05
4092      64259    HGSZ05
4683      67071    HGSZ05
5011      66541    HGSZ05
5024      66549    HGSZ05
5059      64619    HGSZ05
343       44131    CKSZ01
610       44271    CKSZ01
947       44421    CKSZ01
987       44111    CKSZ01
1355      44051    CKSZ01
1379      44291    CKSZ01
1810      44121    CKSZ01
2267      44281    CKSZ01
2296      44299    CKSZ01
2399      44439    CKSZ01
2780      43991    CKSZ01
2805      44061    CKSZ01
3539      44041    CKSZ01
4246      44411    CKSZ01
4645      44289    CKSZ01
4743      44279    CKSZ01
4846      44141    CKSZ01
235       44441    CKSZ03
1100      45239    CKSZ03
1325      44399    CKSZ03
2144      44451    CKSZ03
3017      44009    CKSZ03
3324      44481    CKSZ03
3327      44479    CKSZ03
3333      44539    CKSZ03
3334      44541    CKSZ03
3335      44489    CKSZ03
3698      44119    CKSZ03
3718      44549    CKSZ03
4251      44461    CKSZ03
4408      44391    CKSZ03
4799      44531    CKSZ03
5107      44471    CKSZ03
726       44691    BPSZ03
1204      44699    BPSZ03
1250      44341    BPSZ03
2003      44609    BPSZ03
2470      44231    BPSZ03
2965      44339    BPSZ03
3737      44601    BPSZ03
3858      44779    BPSZ03
3859      44771    BPSZ03
3864      44921    BPSZ03
3865      44919    BPSZ03
3866      44911    BPSZ03
4528      44349    BPSZ03
109       44651    BPSZ01
288       44401    BPSZ01
1357      44791    BPSZ01
2311      44861    BPSZ01
2312      44799    BPSZ01
2806      45019    BPSZ01
2974      44049    BPSZ01
3236      44811    BPSZ01
3591      44069    BPSZ01
3793      44641    BPSZ01
3916      44829    BPSZ01
4466      44059    BPSZ01
4539      44801    BPSZ01
4848      44869    BPSZ01
4945      44809    BPSZ01
5079      44251    BPSZ01
5152      44819    BPSZ01
230       44671    BPSZ02
1212      44669    BPSZ02
1511      44241    BPSZ02
1523      44661    BPSZ02
1633      44679    BPSZ02
1697      44659    BPSZ02
2094      44649    BPSZ02
3860      44831    BPSZ02
3861      44839    BPSZ02
3862      44729    BPSZ02
3917      44821    BPSZ02
4100      44721    BPSZ02
4295      44619    BPSZ02
4688      44701    BPSZ02
4692      44709    BPSZ02
4862      44611    BPSZ02
61        64121    SGSZ01
236       66451    SGSZ01
529       54491    SGSZ01
770       67059    SGSZ01
1568      67049    SGSZ01
1908      67039    SGSZ01
2524      67079    SGSZ01
2794      54501    SGSZ01
3425      66461    SGSZ01
3525      66471    SGSZ01
3953      55109    SGSZ01
4245      67019    SGSZ01
4337      67069    SGSZ01
4702      54651    SGSZ01
4826      67029    SGSZ01
101       67601    SESZ05
456       67309    SESZ05
587       67461    SESZ05
756       65011    SESZ05
1576      67459    SESZ05
1618      67451    SESZ05
1621      67269    SESZ05
1794      67609    SESZ05
2372      67219    SESZ05
2574      67329    SESZ05
3413      67339    SESZ05
3414      67469    SESZ05
3720      67299    SESZ05
4215      67621    SESZ05
4501      67711    SESZ05
78        54481    AMSZ12
1039      55089    AMSZ12
1341      54471    AMSZ12
1364      54351    AMSZ12
1689      55329    AMSZ12
4057      55079    AMSZ12
32        55231    AMSZ10
51        55509    AMSZ10
399       55301    AMSZ10
536       55311    AMSZ10
541       55319    AMSZ10
567       55221    AMSZ10
613       55179    AMSZ10
724       55309    AMSZ10
1098      55229    AMSZ10
1202      54259    AMSZ10
1215      55239    AMSZ10
1528      55219    AMSZ10
1538      55321    AMSZ10
1658      55039    AMSZ10
1696      55009    AMSZ10
2714      55209    AMSZ10
3233      55049    AMSZ10
3913      55211    AMSZ10
4058      55059    AMSZ10
4095      55189    AMSZ10
226       98149    PRSZ06
896       98219    PRSZ06
1077      98121    PRSZ06
1116      98161    PRSZ06
1190      98151    PRSZ06
1211      98181    PRSZ06
1297      98139    PRSZ06
1417      98199    PRSZ06
1809      98041    PRSZ06
1847      98131    PRSZ06
1934      98141    PRSZ06
2030      98051    PRSZ06
2265      98171    PRSZ06
2328      98031    PRSZ06
2538      98061    PRSZ06
2593      98231    PRSZ06
2852      98109    PRSZ06
3212      78149    PRSZ06
3937      98209    PRSZ06
4432      98229    PRSZ06
4629      98129    PRSZ06
33        55351    AMSZ08
105       56061    AMSZ08
211       56041    AMSZ08
517       55251    AMSZ08
570       56191    AMSZ08
646       55361    AMSZ08
1206      56059    AMSZ08
1444      55371    AMSZ08
1539      55241    AMSZ08
1645      56069    AMSZ08
1673      56201    AMSZ08
1973      55331    AMSZ08
2136      56079    AMSZ08
2209      55021    AMSZ08
2459      56071    AMSZ08
3444      55011    AMSZ08
3446      55341    AMSZ08
3449      55349    AMSZ08
3686      56089    AMSZ08
3704      56051    AMSZ08
3764      56049    AMSZ08
3842      55261    AMSZ08
4320      55381    AMSZ08
4992      55339    AMSZ08
216       78279    PRSZ04
448       78109    PRSZ04
827       78119    PRSZ04
1405      78129    PRSZ04
1517      78091    PRSZ04
1977      78269    PRSZ04
2182      77119    PRSZ04
2412      78139    PRSZ04
2981      77129    PRSZ04
3178      78261    PRSZ04
3240      78099    PRSZ04
3512      78251    PRSZ04
3513      78259    PRSZ04
4372      78271    PRSZ04
1348      45249    CKSZ05
1547      45299    CKSZ05
1776      45309    CKSZ05
1795      45259    CKSZ05
1951      45301    CKSZ05
2022      45291    CKSZ05
2135      45311    CKSZ05
2435      45319    CKSZ05
2800      45379    CKSZ05
2801      45371    CKSZ05
2812      45489    CKSZ05
2813      45461    CKSZ05
2850      45469    CKSZ05
3123      45359    CKSZ05
3127      45261    CKSZ05
3128      45271    CKSZ05
3747      45269    CKSZ05
4319      45479    CKSZ05
4485      45361    CKSZ05
4653      45279    CKSZ05
4894      45369    CKSZ05
89        67661    SESZ02
113       65059    SESZ02
300       67521    SESZ02
748       67121    SESZ02
780       67119    SESZ02
815       67139    SESZ02
878       67129    SESZ02
1007      65019    SESZ02
1266      67151    SESZ02
1578      67511    SESZ02
1607      67141    SESZ02
1675      67509    SESZ02
1734      67159    SESZ02
1935      67501    SESZ02
2061      65039    SESZ02
2215      67131    SESZ02
2273      67111    SESZ02
2375      65049    SESZ02
2415      67529    SESZ02
2455      67231    SESZ02
2509      67239    SESZ02
2588      65029    SESZ02
2959      65191    SESZ02
3062      67161    SESZ02
3318      67531    SESZ02
3319      67539    SESZ02
3364      67169    SESZ02
3454      67671    SESZ02
4051      65069    SESZ02
4124      67221    SESZ02
4139      67229    SESZ02
4586      67731    SESZ02
4626      67519    SESZ02
4693      67721    SESZ02
592       55031    AMSZ11
877       55249    AMSZ11
882       55279    AMSZ11
1010      55259    AMSZ11
1344      55269    AMSZ11
3235      55041    AMSZ11
4286      55051    AMSZ11
4394      55081    AMSZ11
4986      55071    AMSZ11
443       99101    CHSZ01
614       99119    CHSZ01
716       99041    CHSZ01
842       99089    CHSZ01
980       99081    CHSZ01
1094      99091    CHSZ01
1295      99031    CHSZ01
1423      99139    CHSZ01
1487      99079    CHSZ01
1488      99071    CHSZ01
1722      99131    CHSZ01
2475      99099    CHSZ01
3622      99111    CHSZ01
3667      99109    CHSZ01
4355      99181    CHSZ01
4427      99129    CHSZ01
5028      99009    CHSZ01
159       67341    SESZ03
307       67331    SESZ03
578       67439    SESZ03
634       67209    SESZ03
697       67261    SESZ03
786       65021    SESZ03
857       67191    SESZ03
1096      67189    SESZ03
1406      67201    SESZ03
1830      65031    SESZ03
1867      67199    SESZ03
2123      67251    SESZ03
2319      67619    SESZ03
2330      67241    SESZ03
2408      65041    SESZ03
2421      67109    SESZ03
2458      67179    SESZ03
2580      67009    SESZ03
2949      67759    SESZ03
3095      67181    SESZ03
3409      67431    SESZ03
3443      67211    SESZ03
3570      67611    SESZ03
3626      67441    SESZ03
3735      65061    SESZ03
3912      67409    SESZ03
3914      67401    SESZ03
4247      67171    SESZ03
4338      67249    SESZ03
4373      67259    SESZ03
4378      67101    SESZ03
4381      67349    SESZ03
4666      67271    SESZ03
4883      67411    SESZ03
5053      67591    SESZ03
23        67319    SESZ04
27        67311    SESZ04
168       67321    SESZ04
374       67449    SESZ04
1047      65809    SESZ04
1087      65801    SESZ04
1862      67301    SESZ04
2048      67279    SESZ04
2085      67549    SESZ04
2279      67351    SESZ04
2441      67541    SESZ04
2723      67761    SESZ04
2760      67769    SESZ04
2926      67369    SESZ04
2967      67381    SESZ04
2968      67391    SESZ04
2969      67399    SESZ04
2970      67421    SESZ04
2971      64729    SESZ04
2999      67641    SESZ04
3000      67649    SESZ04
3001      67691    SESZ04
3002      67699    SESZ04
3317      67389    SESZ04
3564      67589    SESZ04
3719      67291    SESZ04
4038      67379    SESZ04
4039      67371    SESZ04
4387      67361    SESZ04
4595      67581    SESZ04
4882      67419    SESZ04
4982      67429    SESZ04
5064      67599    SESZ04
5090      67359    SESZ04
5095      67421    SESZ04
1546      67021    SESZ07
1597      67091    SESZ07
2544      67011    SESZ07
3632      67089    SESZ07
3954      55101    SESZ07
69        67659    SESZ06
129       67479    SESZ06
238       68059    SESZ06
781       68031    SESZ06
821       67741    SESZ06
883       68011    SESZ06
903       67051    SESZ06
1362      68049    SESZ06
1592      67559    SESZ06
1596      67099    SESZ06
1622      67489    SESZ06
1791      68039    SESZ06
2024      68051    SESZ06
2034      67631    SESZ06
2452      67639    SESZ06
2985      67701    SESZ06
3052      67999    SESZ06
3055      67991    SESZ06
3152      67041    SESZ06
3226      67551    SESZ06
3448      67481    SESZ06
3452      67471    SESZ06
3514      67281    SESZ06
3581      67491    SESZ06
3713      67081    SESZ06
3760      68021    SESZ06
3761      68029    SESZ06
3932      67571    SESZ06
4177      67579    SESZ06
4442      67561    SESZ06
4499      68019    SESZ06
4541      67569    SESZ06
4589      67499    SESZ06
4648      67289    SESZ06
4912      67651    SESZ06
414       65161    PGSZ04
1385      65239    PGSZ04
1628      65269    PGSZ04
1629      65151    PGSZ04
1653      65169    PGSZ04
1803      65079    PGSZ04
2115      65159    PGSZ04
2280      65231    PGSZ04
2391      65289    PGSZ04
2607      65171    PGSZ04
2935      65429    PGSZ04
3521      65279    PGSZ04
3619      65199    PGSZ04
3693      65179    PGSZ04
3773      65089    PGSZ04
4309      65241    PGSZ04
4313      65249    PGSZ04
364       45329    CKSZ06
526       45391    CKSZ06
655       45321    CKSZ06
1370      45411    CKSZ06
2851      45341    CKSZ06
3118      45349    CKSZ06
3119      45331    CKSZ06
3120      45339    CKSZ06
3121      45351    CKSZ06
3122      45399    CKSZ06
3684      45439    CKSZ06
4016      45429    CKSZ06
4020      45409    CKSZ06
4053      45389    CKSZ06
4308      45419    CKSZ06
4329      45421    CKSZ06
4607      45381    CKSZ06
4690      45431    CKSZ06
5008      45401    CKSZ06
1888      77279    PRSZ01
2096      77269    PRSZ01
3279      77339    PRSZ01
449       65551    PGSZ03
531       65219    PGSZ03
734       65251    PGSZ03
1227      65559    PGSZ03
1277      65229    PGSZ03
1766      65149    PGSZ03
1771      65141    PGSZ03
2685      65499    PGSZ03
2754      65531    PGSZ03
2755      65539    PGSZ03
3005      65491    PGSZ03
3064      65339    PGSZ03
3065      65331    PGSZ03
3278      65439    PGSZ03
3391      65541    PGSZ03
3431      65549    PGSZ03
3551      65209    PGSZ03
3751      65009    PGSZ03
3856      65579    PGSZ03
3857      65571    PGSZ03
4160      65201    PGSZ03
4554      65409    PGSZ03
4680      65431    PGSZ03
4686      65341    PGSZ03
4687      65349    PGSZ03
4697      65071    PGSZ03
4754      65081    PGSZ03
83        65271    PGSZ05
407       65319    PGSZ05
485       65311    PGSZ05
549       65321    PGSZ05
647       65189    PGSZ05
698       65309    PGSZ05
873       65329    PGSZ05
1904      65261    PGSZ05
2632      65281    PGSZ05
2744      65381    PGSZ05
2745      65389    PGSZ05
2936      65419    PGSZ05
2997      65561    PGSZ05
2998      65569    PGSZ05
3175      65099    PGSZ05
3237      65371    PGSZ05
3241      65181    PGSZ05
3246      65379    PGSZ05
3248      65399    PGSZ05
3257      65391    PGSZ05
3336      65101    PGSZ05
3358      65301    PGSZ05
3442      65411    PGSZ05
605       45229    SKSZ03
606       45171    SKSZ03
648       45159    SKSZ03
1588      45209    SKSZ03
2054      45179    SKSZ03
2359      45199    SKSZ03
2473      45161    SKSZ03
2795      45059    SKSZ03
2796      45041    SKSZ03
2797      45049    SKSZ03
2798      45031    SKSZ03
2799      45039    SKSZ03
2802      45021    SKSZ03
2803      45029    SKSZ03
2804      45011    SKSZ03
2807      45079    SKSZ03
2808      45071    SKSZ03
2809      45061    SKSZ03
2810      45069    SKSZ03
2811      45051    SKSZ03
2891      44999    SKSZ03
2892      45491    SKSZ03
4714      45189    SKSZ03
4940      45169    SKSZ03
5033      45151    SKSZ03
950       57049    YSSZ06
1340      55281    YSSZ06
1661      59011    YSSZ06
3397      57019    YSSZ06
3402      56099    YSSZ06
3716      57039    YSSZ06
3993      57029    YSSZ06
4043      59021    YSSZ06
583       65601    PGSZ02
590       65609    PGSZ02
1229      65611    PGSZ02
1230      65619    PGSZ02
1280      65221    PGSZ02
2684      65451    PGSZ02
2687      65481    PGSZ02
2688      65489    PGSZ02
2863      65359    PGSZ02
2869      65351    PGSZ02
2937      65469    PGSZ02
3160      65671    PGSZ02
3163      65679    PGSZ02
3253      65461    PGSZ02
3323      65109    PGSZ02
3339      65459    PGSZ02
3870      65449    PGSZ02
3871      65441    PGSZ02
4433      65259    PGSZ02
4494      65091    PGSZ02
4689      65401    PGSZ02
212       40261    CCSZ01
363       48029    CCSZ01
818       40251    CCSZ01
1180      48111    CCSZ01
1313      48039    CCSZ01
1627      48089    CCSZ01
1751      56081    CCSZ01
1922      48059    CCSZ01
1926      48081    CCSZ01
2347      51111    CCSZ01
2771      48131    CCSZ01
3470      51071    CCSZ01
3472      51071    CCSZ01
3569      48071    CCSZ01
3690      48019    CCSZ01
3812      48069    CCSZ01
3833      48119    CCSZ01
4346      41151    CCSZ01
4529      48049    CCSZ01
4960      48079    CCSZ01
156       58201    SBSZ06
602       58191    SBSZ06
1253      58099    SBSZ06
1530      58089    SBSZ06
1665      58091    SBSZ06
1964      58081    SBSZ06
2261      58181    SBSZ06
3699      58071    SBSZ06
4121      58079    SBSZ06
1909      58171    SBSZ07
2615      58141    SBSZ07
4389      58161    SBSZ07
609       47091    SBSZ08
1013      47821    SBSZ08
1066      47071    SBSZ08
1176      47801    SBSZ08
1409      47119    SBSZ08
1701      47089    SBSZ08
2204      47081    SBSZ08
2277      47111    SBSZ08
2493      47151    SBSZ08
2519      47811    SBSZ08
3161      47189    SBSZ08
3239      47121    SBSZ08
3258      47129    SBSZ08
3500      47179    SBSZ08
3549      47109    SBSZ08
3642      47199    SBSZ08
3817      47169    SBSZ08
3966      47101    SBSZ08
4223      47141    SBSZ08
4253      47061    SBSZ08
4505      47099    SBSZ08
4514      47131    SBSZ08
116       01239    KLSZ09
1757      01211    KLSZ09
2948      01411    KLSZ09
4004      01421    KLSZ09
4875      01329    KLSZ09
4876      01219    KLSZ09
4916      01341    KLSZ09
325       26131    TSSZ04
356       26069    TSSZ04
366       25399    TSSZ04
566       26099    TSSZ04
679       26151    TSSZ04
769       24621    TSSZ04
1471      26031    TSSZ04
1638      26119    TSSZ04
1768      26129    TSSZ04
1992      26171    TSSZ04
2126      24619    TSSZ04
2222      24611    TSSZ04
2488      26161    TSSZ04
2562      26061    TSSZ04
2571      26029    TSSZ04
2572      26019    TSSZ04
2573      26081    TSSZ04
2578      26071    TSSZ04
2623      26089    TSSZ04
2730      24709    TSSZ04
2732      24719    TSSZ04
2739      25561    TSSZ04
2740      25569    TSSZ04
2742      25571    TSSZ04
2747      25591    TSSZ04
2768      25671    TSSZ04
2784      26101    TSSZ04
2785      26091    TSSZ04
2824      25821    TSSZ04
2825      25661    TSSZ04
2826      25669    TSSZ04
2837      26059    TSSZ04
2861      25691    TSSZ04
3363      24601    TSSZ04
3495      26021    TSSZ04
3553      26049    TSSZ04
3691      26011    TSSZ04
3877      26111    TSSZ04
4073      26051    TSSZ04
4074      26041    TSSZ04
4075      26039    TSSZ04
4208      24609    TSSZ04
4221      26121    TSSZ04
4376      26109    TSSZ04
4437      26141    TSSZ04
4518      24699    TSSZ04
4931      26079    TSSZ04
5031      24629    TSSZ04
254       26379    TSSZ05
729       26311    TSSZ05
981       26441    TSSZ05
1072      26451    TSSZ05
1464      26409    TSSZ05
1565      26299    TSSZ05
1700      26259    TSSZ05
1715      26399    TSSZ05
1778      26331    TSSZ05
1875      26349    TSSZ05
2060      26269    TSSZ05
2403      26369    TSSZ05
2672      26279    TSSZ05
2689      25641    TSSZ05
2707      26289    TSSZ05
2741      25579    TSSZ05
2746      25599    TSSZ05
2748      25601    TSSZ05
2749      25609    TSSZ05
2750      25611    TSSZ05
2751      25621    TSSZ05
2752      25631    TSSZ05
2781      25701    TSSZ05
2782      25709    TSSZ05
2843      26249    TSSZ05
2896      25651    TSSZ05
3647      26431    TSSZ05
4158      26221    TSSZ05
4203      26389    TSSZ05
4240      26429    TSSZ05
4512      26461    TSSZ05
5027      26321    TSSZ05
5070      26211    TSSZ05
5156      26419    TSSZ05
2062      27129    WCSZ03
806       27171    WCSZ02
952       27169    WCSZ02
2402      27179    WCSZ02
3837      27121    WCSZ02
165       28221    JESZ05
718       20069    JESZ05
2313      28261    JESZ05
3181      20271    JESZ05
3843      28241    JESZ05
4263      20089    JESZ05
4858      28251    JESZ05
4954      28231    JESZ05
2340      43781    THSZ03
2961      43771    THSZ03
416       43671    THSZ04
2830      30119    THSZ04
2832      30129    THSZ04
2834      30109    THSZ04
3633      44171    THSZ04
4453      30089    THSZ01
171       28141    THSZ06
403       28129    THSZ06
408       28139    THSZ06
437       28121    THSZ06
931       28149    THSZ06
1226      43761    THSZ06
1287      28131    THSZ06
1448      28111    THSZ06
1835      28119    THSZ06
3895      43459    THSZ06
4145      43751    THSZ06
1022      73041    PLSZ04
2440      73019    PLSZ04
3676      73049    PLSZ04
37        97089    CHSZ02
153       97069    CHSZ02
231       98079    CHSZ02
516       97169    CHSZ02
803       99049    CHSZ02
954       97189    CHSZ02
1123      97159    CHSZ02
1359      97181    CHSZ02
1460      97179    CHSZ02
1663      99011    CHSZ02
1745      97149    CHSZ02
1748      97141    CHSZ02
1759      98069    CHSZ02
1874      97171    CHSZ02
1886      97059    CHSZ02
1898      97151    CHSZ02
1937      97079    CHSZ02
1941      99029    CHSZ02
1985      99019    CHSZ02
2038      97079    CHSZ02
2110      97049    CHSZ02
2180      97209    CHSZ02
2323      99039    CHSZ02
2392      97099    CHSZ02
2468      97161    CHSZ02
3220      97301    CHSZ02
3342      97321    CHSZ02
3403      97331    CHSZ02
3580      97311    CHSZ02
4102      97019    CHSZ02
4892      99021    CHSZ02
5038      98071    CHSZ02
5148      97039    CHSZ02
779       11379    QTSZ02
2501      11179    QTSZ02
2511      11259    QTSZ02
3115      11381    QTSZ02
3116      11409    QTSZ02
3272      11389    QTSZ02
3523      11261    QTSZ02
3839      11189    QTSZ02
3902      11401    QTSZ02
121       95151    CHSZ03
402       95141    CHSZ03
483       95089    CHSZ03
560       95149    CHSZ03
562       95049    CHSZ03
571       96219    CHSZ03
595       95071    CHSZ03
626       99171    CHSZ03
709       95029    CHSZ03
835       95019    CHSZ03
843       95209    CHSZ03
1454      95109    CHSZ03
1524      95131    CHSZ03
1662      95129    CHSZ03
1676      99161    CHSZ03
2067      95051    CHSZ03
2207      95171    CHSZ03
2248      95179    CHSZ03
2450      95011    CHSZ03
3071      96429    CHSZ03
3072      96421    CHSZ03
3073      96431    CHSZ03
3494      95169    CHSZ03
3544      95041    CHSZ03
3637      95039    CHSZ03
3677      99189    CHSZ03
3853      95061    CHSZ03
3854      95069    CHSZ03
3906      95091    CHSZ03
3968      95099    CHSZ03
4113      95081    CHSZ03
4225      95161    CHSZ03
4315      95191    CHSZ03
4504      95181    CHSZ03
4594      95189    CHSZ03
4905      95079    CHSZ03
5061      95139    CHSZ03
5119      95159    CHSZ03
3099      06029    OTSZ02
3331      05012    OTSZ02
4772      05013    OTSZ02
103       81199    MPSZ01
213       91121    MPSZ01
283       91051    MPSZ01
423       91071    MPSZ01
649       91151    MPSZ01
886       91161    MPSZ01
918       91131    MPSZ01
1146      82051    MPSZ01
1959      82071    MPSZ01
2463      91061    MPSZ01
2628      91069    MPSZ01
2670      92161    MPSZ01
3819      91059    MPSZ01
3952      91099    MPSZ01
4035      91089    MPSZ01
4173      91041    MPSZ01
5135      91079    MPSZ01
5150      91049    MPSZ01
162       81011    GLSZ04
189       80149    GLSZ04
227       80279    GLSZ04
309       80251    GLSZ04
326       81169    GLSZ04
354       80071    GLSZ04
447       81051    GLSZ04
512       80069    GLSZ04
792       80259    GLSZ04
800       80091    GLSZ04
816       81069    GLSZ04
934       81229    GLSZ04
1089      81129    GLSZ04
1113      81221    GLSZ04
1571      81049    GLSZ04
1657      81029    GLSZ04
1707      81231    GLSZ04
1755      81031    GLSZ04
1939      81119    GLSZ04
2025      80229    GLSZ04
2189      81189    GLSZ04
2233      80239    GLSZ04
2437      81219    GLSZ04
2465      81099    GLSZ04
2636      80231    GLSZ04
3145      80289    GLSZ04
3375      80249    GLSZ04
3746      81211    GLSZ04
3910      81151    GLSZ04
3911      81159    GLSZ04
3925      81171    GLSZ04
3938      80269    GLSZ04
3943      80089    GLSZ04
3946      81089    GLSZ04
3947      81081    GLSZ04
4003      81149    GLSZ04
4164      81209    GLSZ04
4165      81109    GLSZ04
4268      81181    GLSZ04
4440      81201    GLSZ04
4590      81179    GLSZ04
4889      80119    GLSZ04
4896      81139    GLSZ04
5055      81161    GLSZ04
5085      81091    GLSZ04
59        45101    SKSZ02
202       45181    SKSZ02
765       45111    SKSZ02
1358      45109    SKSZ02
1395      45099    SKSZ02
1727      45221    SKSZ02
1737      45129    SKSZ02
1813      45091    SKSZ02
2704      46381    SKSZ02
2964      45139    SKSZ02
3712      45201    SKSZ02
3991      45211    SKSZ02
4708      45191    SKSZ02
4718      45119    SKSZ02
71        58479    WDSZ04
331       46979    WDSZ04
334       46649    WDSZ04
1316      46331    WDSZ04
1347      46999    WDSZ04
1554      47499    WDSZ04
1555      47491    WDSZ04
1557      47509    WDSZ04
1584      47521    WDSZ04
1595      47529    WDSZ04
1603      47539    WDSZ04
1780      58439    WDSZ04
1839      46969    WDSZ04
2058      46659    WDSZ04
2158      47569    WDSZ04
2173      47579    WDSZ04
2658      46651    WDSZ04
2786      46981    WDSZ04
2787      46989    WDSZ04
3537      46221    WDSZ04
3733      46961    WDSZ04
4001      47589    WDSZ04
4166      47511    WDSZ04
4400      46991    WDSZ04
4536      58449    WDSZ04
4706      46971    WDSZ04
5098      58461    WDSZ04
5102      47501    WDSZ04
5144      46951    WDSZ04
112       46549    WDSZ05
120       46529    WDSZ05
145       46349    WDSZ05
830       46339    WDSZ05
863       46379    WDSZ05
938       46369    WDSZ05
1617      45591    WDSZ05
1678      46361    WDSZ05
1754      46359    WDSZ05
1884      46341    WDSZ05
1944      46611    WDSZ05
2089      46371    WDSZ05
2177      46539    WDSZ05
2395      46591    WDSZ05
3098      46491    WDSZ05
3330      45599    WDSZ05
3538      46229    WDSZ05
3685      46629    WDSZ05
3823      46351    WDSZ05
4071      45581    WDSZ05
4072      45589    WDSZ05
4288      46621    WDSZ05
4553      46619    WDSZ05
4784      46329    WDSZ05
294       59781    YSSZ03
395       59411    YSSZ03
446       59389    YSSZ03
561       59399    YSSZ03
862       59171    YSSZ03
928       59409    YSSZ03
1049      59649    YSSZ03
1239      59591    YSSZ03
1291      59391    YSSZ03
1714      59639    YSSZ03
1732      59461    YSSZ03
1829      59419    YSSZ03
1836      59581    YSSZ03
1995      59601    YSSZ03
2074      59381    YSSZ03
2324      59599    YSSZ03
2349      59359    YSSZ03
2448      59609    YSSZ03
2634      59401    YSSZ03
2692      59471    YSSZ03
2783      59621    YSSZ03
2789      59771    YSSZ03
3173      59579    YSSZ03
3568      59809    YSSZ03
3601      59811    YSSZ03
3604      59791    YSSZ03
3726      59819    YSSZ03
4017      59641    YSSZ03
4101      59801    YSSZ03
4281      59451    YSSZ03
4330      59469    YSSZ03
4604      59651    YSSZ03
5138      59181    YSSZ03
2         32071    WCSZ01
66        30059    WCSZ01
157       31059    WCSZ01
158       31081    WCSZ01
228       31171    WCSZ01
369       31039    WCSZ01
478       31089    WCSZ01
499       31041    WCSZ01
503       31121    WCSZ01
558       31169    WCSZ01
656       31179    WCSZ01
686       31011    WCSZ01
725       30029    WCSZ01
798       27211    WCSZ01
949       31079    WCSZ01
968       31149    WCSZ01
969       31141    WCSZ01
1001      31161    WCSZ01
1015      30019    WCSZ01
1075      31029    WCSZ01
1110      32119    WCSZ01
1132      27231    WCSZ01
1136      32081    WCSZ01
1194      31051    WCSZ01
1196      32051    WCSZ01
1223      32109    WCSZ01
1262      30051    WCSZ01
1294      27221    WCSZ01
1314      31139    WCSZ01
1329      31129    WCSZ01
1380      32049    WCSZ01
1396      24049    WCSZ01
1425      30011    WCSZ01
1476      32061    WCSZ01
1500      27291    WCSZ01
1569      32101    WCSZ01
1587      32111    WCSZ01
1684      32079    WCSZ01
1825      27069    WCSZ01
1958      31201    WCSZ01
1966      27051    WCSZ01
1968      32039    WCSZ01
2014      27031    WCSZ01
2140      32069    WCSZ01
2294      27189    WCSZ01
2317      30039    WCSZ01
2438      27199    WCSZ01
2461      45241    WCSZ01
2485      27281    WCSZ01
2494      32041    WCSZ01
2495      31069    WCSZ01
2560      31131    WCSZ01
2576      31031    WCSZ01
2587      27021    WCSZ01
2622      27311    WCSZ01
2627      31211    WCSZ01
2683      31151    WCSZ01
2848      31159    WCSZ01
2909      30041    WCSZ01
2910      30049    WCSZ01
2941      27071    WCSZ01
3092      27219    WCSZ01
3150      27251    WCSZ01
3288      27241    WCSZ01
3428      27041    WCSZ01
3432      27061    WCSZ01
3436      27209    WCSZ01
3438      27011    WCSZ01
3610      45251    WCSZ01
3682      32059    WCSZ01
3775      32031    WCSZ01
3934      31061    WCSZ01
4005      31191    WCSZ01
4026      30091    WCSZ01
4028      30099    WCSZ01
4029      30031    WCSZ01
4089      27261    WCSZ01
4106      31049    WCSZ01
4186      31009    WCSZ01
4385      30021    WCSZ01
4393      31021    WCSZ01
4731      31071    WCSZ01
4739      31199    WCSZ01
4808      27181    WCSZ01
4812      34109    WCSZ01
4813      34101    WCSZ01
4944      31019    WCSZ01
357       59251    YSSZ09
707       59061    YSSZ09
782       59309    YSSZ09
937       59331    YSSZ09
948       59079    YSSZ09
1221      57129    YSSZ09
1293      59139    YSSZ09
1363      59111    YSSZ09
1486      59121    YSSZ09
1561      59129    YSSZ09
1651      59301    YSSZ09
1695      59089    YSSZ09
1859      59311    YSSZ09
2125      57119    YSSZ09
2147      59081    YSSZ09
2179      59119    YSSZ09
2439      59131    YSSZ09
2460      59149    YSSZ09
2584      59269    YSSZ09
2650      59511    YSSZ09
2792      58991    YSSZ09
2960      59319    YSSZ09
3192      59159    YSSZ09
3193      59141    YSSZ09
3198      59091    YSSZ09
3423      59541    YSSZ09
3679      59261    YSSZ09
3826      57089    YSSZ09
4007      59109    YSSZ09
4008      59101    YSSZ09
4032      59279    YSSZ09
4070      59671    YSSZ09
4366      59551    YSSZ09
4547      59271    YSSZ09
4634      59521    YSSZ09
182       46299    WDSZ01
223       46191    WDSZ01
1703      46008    WDSZ01
2178      46009    WDSZ01
2928      46311    WDSZ01
3006      46321    WDSZ01
3876      46301    WDSZ01
4543      46271    WDSZ01
4782      46639    WDSZ01
178       59179    YSSZ02
675       59249    YSSZ02
955       59221    YSSZ02
989       59201    YSSZ02
1192      59199    YSSZ02
1551      59241    YSSZ02
1698      59211    YSSZ02
1890      59231    YSSZ02
3195      59169    YSSZ02
3199      59099    YSSZ02
3936      59191    YSSZ02
4031      59189    YSSZ02
4488      59259    YSSZ02
4615      59529    YSSZ02
4809      59209    YSSZ02
5009      59229    YSSZ02
5017      59239    YSSZ02
5036      59219    YSSZ02
14        46261    WDSZ02
370       46449    WDSZ02
405       46661    WDSZ02
810       46391    WDSZ02
1076      46401    WDSZ02
1373      46399    WDSZ02
1846      46681    WDSZ02
1902      46251    WDSZ02
2318      46431    WDSZ02
2401      47581    WDSZ02
2472      46459    WDSZ02
2549      46679    WDSZ02
2563      46699    WDSZ02
2618      46411    WDSZ02
3007      46281    WDSZ02
3008      46289    WDSZ02
3188      46441    WDSZ02
3623      46671    WDSZ02
3734      46669    WDSZ02
4280      46421    WDSZ02
4359      46641    WDSZ02
4736      46429    WDSZ02
4783      46631    WDSZ02
4934      46439    WDSZ02
5141      46279    WDSZ02
19        46709    WDSZ06
128       46189    WDSZ06
361       46079    WDSZ06
384       46589    WDSZ06
436       46499    WDSZ06
462       46139    WDSZ06
753       46119    WDSZ06
788       46531    WDSZ06
973       46551    WDSZ06
1232      46201    WDSZ06
1422      46511    WDSZ06
1672      46579    WDSZ06
1736      46521    WDSZ06
1743      46581    WDSZ06
2133      46241    WDSZ06
2236      46181    WDSZ06
2342      46559    WDSZ06
2422      46209    WDSZ06
2506      46519    WDSZ06
2644      46291    WDSZ06
2927      46319    WDSZ06
3384      46561    WDSZ06
3385      46571    WDSZ06
3386      46569    WDSZ06
3806      46091    WDSZ06
3889      46501    WDSZ06
3923      46249    WDSZ06
4170      46199    WDSZ06
4278      46019    WDSZ06
4522      46129    WDSZ06
4610      46509    WDSZ06
4611      46171    WDSZ06
4675      46541    WDSZ06
4811      46011    WDSZ06
4854      46071    WDSZ06
4856      46179    WDSZ06
44        58019    SBSZ02
148       58039    SBSZ02
338       58031    SBSZ02
540       57131    SBSZ02
752       57139    SBSZ02
1092      58399    SBSZ02
1591      58549    SBSZ02
2939      58261    SBSZ02
3851      58029    SBSZ02
3852      58021    SBSZ02
4179      58011    SBSZ02
466       46041    SKSZ01
711       46049    SKSZ01
944       45149    SKSZ01
1134      45121    SKSZ01
1247      49121    SKSZ01
1324      45141    SKSZ01
1339      49129    SKSZ01
2078      46031    SKSZ01
2081      46039    SKSZ01
2187      46059    SKSZ01
2210      49181    SKSZ01
2219      49109    SKSZ01
2705      46389    SKSZ01
2816      49091    SKSZ01
2817      49099    SKSZ01
2862      46029    SKSZ01
2866      46021    SKSZ01
2963      45131    SKSZ01
3527      46051    SKSZ01
3897      49119    SKSZ01
4258      49189    SKSZ01
4897      49101    SKSZ01
4938      49111    SKSZ01
138       49149    SKSZ05
144       49169    SKSZ05
619       49089    SKSZ05
1044      49151    SKSZ05
1167      49069    SKSZ05
1420      49059    SKSZ05
1437      49171    SKSZ05
1601      49079    SKSZ05
1770      45449    SKSZ05
1841      49061    SKSZ05
1881      45441    SKSZ05
1918      49179    SKSZ05
1987      49051    SKSZ05
2464      49159    SKSZ05
2469      49141    SKSZ05
2526      49071    SKSZ05
4382      49081    SKSZ05
20        46831    WDSZ03
97        46809    WDSZ03
99        47551    WDSZ03
102       46749    WDSZ03
176       46791    WDSZ03
257       46689    WDSZ03
421       47571    WDSZ03
544       46801    WDSZ03
669       46799    WDSZ03
703       47611    WDSZ03
1030      46811    WDSZ03
1174      47549    WDSZ03
1400      47609    WDSZ03
1443      46769    WDSZ03
1456      46851    WDSZ03
1900      46779    WDSZ03
2104      46841    WDSZ03
2111      47601    WDSZ03
2152      47559    WDSZ03
2191      46821    WDSZ03
2229      46739    WDSZ03
2234      47671    WDSZ03
2307      46489    WDSZ03
2354      46869    WDSZ03
2657      47619    WDSZ03
2720      47759    WDSZ03
2788      47751    WDSZ03
2814      46479    WDSZ03
2914      46859    WDSZ03
3356      47599    WDSZ03
3357      47641    WDSZ03
3722      47659    WDSZ03
3724      47651    WDSZ03
3824      46469    WDSZ03
4006      47561    WDSZ03
4087      46861    WDSZ03
4148      46781    WDSZ03
4312      47661    WDSZ03
4322      47681    WDSZ03
4323      47649    WDSZ03
4454      46761    WDSZ03
4654      47541    WDSZ03
4694      46691    WDSZ03
4775      47591    WDSZ03
4786      46789    WDSZ03
4839      46871    WDSZ03
4937      46771    WDSZ03
4969      46419    WDSZ03
5015      46879    WDSZ03
5075      58309    WDSZ03
5143      46409    WDSZ03
64        58151    SBSZ03
137       58101    SBSZ03
279       58299    SBSZ03
902       58311    SBSZ03
1217      58281    SBSZ03
1349      58389    SBSZ03
1705      58279    SBSZ03
1990      58211    SBSZ03
2029      58421    SBSZ03
2041      58111    SBSZ03
2084      58009    SBSZ03
2333      58391    SBSZ03
2653      58371    SBSZ03
2655      58379    SBSZ03
2724      58319    SBSZ03
2726      58229    SBSZ03
2756      58221    SBSZ03
2758      58321    SBSZ03
2763      58259    SBSZ03
3254      58251    SBSZ03
3260      58291    SBSZ03
3455      58289    SBSZ03
3585      58571    SBSZ03
4112      58241    SBSZ03
4380      58219    SBSZ03
4448      58271    SBSZ03
4727      58249    SBSZ03
204       46451    WDSZ07
278       47201    WDSZ07
351       47039    WDSZ07
2143      46269    WDSZ07
2938      46309    WDSZ07
3974      47029    WDSZ07
3977      47019    WDSZ07
4624      47201    WDSZ07
666       58049    SBSZ01
1581      58541    SBSZ01
2879      58519    SBSZ01
2880      58511    SBSZ01
2881      58529    SBSZ01
2882      58521    SBSZ01
2883      58531    SBSZ01
2885      58539    SBSZ01
2940      58269    SBSZ01
3204      58059    SBSZ01
3347      58069    SBSZ01
3365      58619    SBSZ01
3368      58621    SBSZ01
3374      58601    SBSZ01
3377      58611    SBSZ01
4994      58609    SBSZ01
424       47069    WDSZ08
2638      47049    WDSZ08
2815      46471    WDSZ08
3383      46711    WDSZ08
3555      46481    WDSZ08
3759      46461    WDSZ08
3810      47059    WDSZ08
4927      46721    WDSZ08
149       58031    SBSZ05
630       58189    SBSZ05
642       58199    SBSZ05
644       58129    SBSZ05
1458      58051    SBSZ05
1864      58331    SBSZ05
1887      58491    SBSZ05
2055      58041    SBSZ05
2227      58179    SBSZ05
2297      58339    SBSZ05
2417      58509    SBSZ05
2597      58481    SBSZ05
2757      58119    SBSZ05
2884      58061    SBSZ05
3197      58501    SBSZ05
3528      58489    SBSZ05
3605      58209    SBSZ05
3710      58109    SBSZ05
4172      58139    SBSZ05
4352      58499    SBSZ05
4657      58159    SBSZ05
41        49249    LKSZ01
282       33029    LKSZ01
306       49209    LKSZ01
528       49239    LKSZ01
596       34019    LKSZ01
1037      33049    LKSZ01
1153      33059    LKSZ01
1244      33041    LKSZ01
1254      34051    LKSZ01
1384      34011    LKSZ01
1431      33019    LKSZ01
1560      34039    LKSZ01
1930      33051    LKSZ01
2118      49229    LKSZ01
2336      34059    LKSZ01
2393      34041    LKSZ01
2423      49211    LKSZ01
2503      33039    LKSZ01
2546      34049    LKSZ01
2589      32089    LKSZ01
3010      34009    LKSZ01
3893      34021    LKSZ01
4344      34031    LKSZ01
4361      34029    LKSZ01
4369      49199    LKSZ01
4616      49219    LKSZ01
4985      33021    LKSZ01
5069      33031    LKSZ01
5077      33011    LKSZ01
439       47079    SBSZ09
505       46741    SBSZ09
1599      46911    SBSZ09
1630      46901    SBSZ09
1648      46921    SBSZ09
1818      47829    SBSZ09
1940      47629    SBSZ09
2149      46731    SBSZ09
2247      46941    SBSZ09
2491      46931    SBSZ09
3180      47621    SBSZ09
3418      46719    SBSZ09
3499      46891    SBSZ09
4151      58301    SBSZ09
4508      46881    SBSZ09
4831      46729    SBSZ09
201       47819    SBSZ04
312       58121    SBSZ04
876       58459    SBSZ04
995       58349    SBSZ04
1298      58351    SBSZ04
1480      58329    SBSZ04
2026      58409    SBSZ04
2260      58131    SBSZ04
2288      58429    SBSZ04
2362      58451    SBSZ04
2433      47809    SBSZ04
2631      58359    SBSZ04
3492      58369    SBSZ04
3594      58411    SBSZ04
3736      58341    SBSZ04
3905      58361    SBSZ04
4267      58149    SBSZ04
4379      58381    SBSZ04
4420      58169    SBSZ04
4635      58401    SBSZ04
4962      58419    SBSZ04
637       47051    WDSZ09
977       46169    WDSZ09
1009      47041    WDSZ09
1178      46161    WDSZ09
1234      46159    WDSZ09
1769      46109    WDSZ09
2305      47031    WDSZ09
2661      46131    WDSZ09
2706      46088    WDSZ09
3477      46069    WDSZ09
3599      46149    WDSZ09
3618      46101    WDSZ09
4153      46141    WDSZ09
4220      47011    WDSZ09
4832      47021    WDSZ09
4849      46151    WDSZ09
4924      46121    WDSZ09
4990      46111    WDSZ09
555       71049    PLSZ05
1079      64139    PLSZ05
1299      64189    PLSZ05
2643      71189    PLSZ05
3076      73029    PLSZ05
3077      74019    PLSZ05
3080      74029    PLSZ05
3083      73039    PLSZ05
3084      64199    PLSZ05
3609      64179    PLSZ05
4178      64159    PLSZ05
4941      64169    PLSZ05
5065      64149    PLSZ05
322       57111    MDSZ02
523       57061    MDSZ02
767       57051    MDSZ02
2292      57121    MDSZ02
3588      58579    MDSZ02
3786      48141    MDSZ02
253       57149    YSSZ07
804       48109    YSSZ07
831       48101    YSSZ07
2170      57031    YSSZ07
3393      56091    YSSZ07
3394      57011    YSSZ07
3645      48149    YSSZ07
3961      57041    YSSZ07
3999      48091    YSSZ07
4465      57021    YSSZ07
4477      57141    YSSZ07
4852      48099    YSSZ07
233       53189    BSSZ01
313       53091    BSSZ01
348       53019    BSSZ01
352       53079    BSSZ01
380       53089    BSSZ01
440       53061    BSSZ01
554       53191    BSSZ01
717       53039    BSSZ01
720       53291    BSSZ01
728       53299    BSSZ01
836       53331    BSSZ01
1014      53081    BSSZ01
1107      53361    BSSZ01
1111      56269    BSSZ01
1252      53069    BSSZ01
1552      53141    BSSZ01
1843      53171    BSSZ01
2050      53111    BSSZ01
2130      53181    BSSZ01
2186      53339    BSSZ01
2331      53161    BSSZ01
2334      53201    BSSZ01
2478      54069    BSSZ01
2592      53369    BSSZ01
3051      05349    BSSZ01
3057      53351    BSSZ01
3061      53359    BSSZ01
3070      53341    BSSZ01
3155      53049    BSSZ01
3156      53041    BSSZ01
3157      53059    BSSZ01
3158      53041    BSSZ01
3159      53179    BSSZ01
3224      53021    BSSZ01
3225      53029    BSSZ01
4109      53131    BSSZ01
4119      54629    BSSZ01
4277      53199    BSSZ01
4357      53121    BSSZ01
4459      53209    BSSZ01
4698      53011    BSSZ01
4724      53329    BSSZ01
4725      53321    BSSZ01
4757      53071    BSSZ01
4936      53151    BSSZ01
5020      54619    BSSZ01
5081      53099    BSSZ01
502       54011    AMSZ05
557       54229    AMSZ05
1593      56261    AMSZ05
3986      54239    AMSZ05
4097      54211    AMSZ05
4134      54621    AMSZ05
4159      54061    AMSZ05
4456      54219    AMSZ05
4540      56289    AMSZ05
4658      54611    AMSZ05
4997      54181    AMSZ05
5147      54169    AMSZ05
251       54321    AMSZ04
768       54247    AMSZ04
838       54091    AMSZ04
1416      54081    AMSZ04
2031      54331    AMSZ04
2431      54248    AMSZ04
2708      54019    AMSZ04
3918      54311    AMSZ04
4061      54071    AMSZ04
205       53391    BSSZ02
340       53219    BSSZ02
347       53159    BSSZ02
508       51131    BSSZ02
653       53139    BSSZ02
744       54099    BSSZ02
1086      53399    BSSZ02
1377      53389    BSSZ02
1877      53149    BSSZ02
1998      54079    BSSZ02
2015      54539    BSSZ02
2467      53169    BSSZ02
2673      53129    BSSZ02
3107      53319    BSSZ02
3108      53311    BSSZ02
3273      52011    BSSZ02
3994      54089    BSSZ02
4129      53249    BSSZ02
4167      53371    BSSZ02
4259      53239    BSSZ02
4356      53309    BSSZ02
4371      53301    BSSZ02
4535      53381    BSSZ02
4612      53379    BSSZ02
4744      53119    BSSZ02
1589      25781    TSSZ06
2564      25729    TSSZ06
2570      25751    TSSZ06
2678      25801    TSSZ06
2823      25771    TSSZ06
2827      25719    TSSZ06
2828      25711    TSSZ06
2829      25741    TSSZ06
2893      25791    TSSZ06
2897      25761    TSSZ06
3269      25059    TSSZ06</code></pre>
</div>
</div>
<p>We will save the output into rds format for future use.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(busstop_mpsz, <span class="st">"data/rds/busstop_mpsz.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will then append the planning subzone code (<strong>SUBZONE_C</strong>) from busstop_mpsz data frame onto origintrip7_9 dataframe using the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>origintrip_7_9_subzone <span class="ot">&lt;-</span> <span class="fu">left_join</span>(origintrip_7_9,busstop_mpsz,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"ORIGIN_PT_CODE"</span> <span class="ot">=</span> <span class="st">"BUS_STOP_N"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">ORIGIN_BS =</span> ORIGIN_PT_CODE, </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">ORIGIN_SZ =</span> SUBZONE_C)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let us check for duplicate records:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>duplicate <span class="ot">&lt;-</span> origintrip_7_9_subzone <span class="sc">%&gt;%</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by_all</span>() <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">n</span>()<span class="sc">&gt;</span><span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(duplicate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>From the above, we know that there are duplicate records. Hence, we will use the following code chunk to retain only the unique records.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>origin_data <span class="ot">&lt;-</span> <span class="fu">unique</span>(origintrip_7_9_subzone)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let us confirm if there are any duplicate records in the above dataframe:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>duplicate2 <span class="ot">&lt;-</span> origin_data <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by_all</span>() <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">n</span>()<span class="sc">&gt;</span><span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(duplicate2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Since there are no rows returned, it means that origin_data has no duplicates and we can proceed to the next step.</p>
<p>We will then update the origin_data data frame with the planning subzone codes found in mpsz using the following code chunk.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>mpsz_origin_data <span class="ot">&lt;-</span> <span class="fu">left_join</span>(mpsz, origin_data,</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"SUBZONE_C"</span> <span class="ot">=</span> <span class="st">"ORIGIN_SZ"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="choropleth-visualisation" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="choropleth-visualisation"><span class="header-section-number">5</span> Choropleth Visualisation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(mpsz_origin_data)<span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"TRIPS"</span>, </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">n =</span> <span class="dv">5</span>, </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"quantile"</span>,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"Blues"</span>, </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Passenger Trips"</span>)<span class="sc">+</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Passenger Trips Generated at Planning Subzone Level"</span>,</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.2</span>,</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.45</span>,</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.35</span>,</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>)<span class="sc">+</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type =</span> <span class="st">"8star"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>()<span class="sc">+</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_grid</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>)<span class="sc">+</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_credits</span>(<span class="st">"Source: Planning Subzone boundary from URA and </span><span class="sc">\n</span><span class="st">Passenger Trips Data from LTA"</span>, <span class="at">size =</span> <span class="fl">0.5</span>, <span class="at">position =</span> <span class="fu">c</span>(<span class="st">"left"</span>, <span class="st">"bottom"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://quarto.org/">Published with Quarto |</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://www.netlify.com/">Hosted by Netlify</a>
  </li>  
</ul>
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 Copyright 2023, Goh Si Hui
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>